package com.puente4podcast.puente4podcast;

import com.puente4podcast.puente4podcast.models.*;
import com.puente4podcast.puente4podcast.repositories.*;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

@SpringBootApplication
public class Puente4podcastApplication {

	public static void main(String[] args) {
		SpringApplication.run(Puente4podcastApplication.class, args);
	}
	@Bean
	public CommandLineRunner initData(PodcastUserRepository podcastUserRepository, PodcastRepository podcastRepository, SeasonRepository seasonRepository, EpisodeRepository episodeRepository, ArchiveRepository archiveRepository) {
		return args -> {
			PodcastUser adminUser = new PodcastUser("admin", "admin", "admin", "admin@puente4podcast.com", "chile", "admin");

			Podcast puente4podcast = new Podcast("puente4podcast", "El podcast de la gente que ve el mundo, de otra manera!", "https://imgur.com/rJh1nKq");

			Season season1 = new Season((long) 1);
			Season season2 = new Season((long) 2);
			Season season3 = new Season((long) 3);

			Episode episode1x01 = new Episode((byte) 1, (byte) 1, "Cosas como Viajes en el tiempo, Nintendo y experimentos rusos", "https://i.ytimg.com/vi/HCZbEWn328U/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCW9N3Sq2ERk7rNJ6-ZD-koaGSlGg", "https://www.youtube.com/watch?v=HCZbEWn328U", "https://www.ivoox.com/1x01-cosas-como-viajes-tiempo-videojuegos-audios-mp3_rf_60420409_1.html", "1:31:13", "canon");
			Episode episode1x02 = new Episode((byte) 1, (byte) 2, "Cosas como Piratas, tu muerte y Elon Musk", "https://i.ytimg.com/vi/lLdsVHjsQz0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB9glm31mlzCkeTteRxfXe64MHonw", "https://www.youtube.com/watch?v=lLdsVHjsQz0", "https://www.ivoox.com/1x02-cosas-como-piratas-tu-muerte-elon-audios-mp3_rf_60770749_1.html", "1:25:44", "canon");
			Episode episode1x03 = new Episode((byte) 1, (byte) 3, "Cosas como Pelis de libros, parásitos y expresiones", "https://i.ytimg.com/vi/X3ivw_LONtk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDVZJHcDl3BDHXQoHFhBiaZGsxBbQ", "https://www.youtube.com/watch?v=X3ivw_LONtk", "https://www.ivoox.com/1x03-cosas-como-pelis-libros-parasitos-y-audios-mp3_rf_61090555_1.html", "1:35:51", "canon");
			Episode episode1x04 = new Episode((byte) 1, (byte) 4, "Cosas como Premios IgNovel, especias y espadas de videojuegos", "https://i.ytimg.com/vi/kX6Pe98rbSY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC_A67TZ5A1LCW7Fa4rVY8B5quJYQ", "https://www.youtube.com/watch?v=kX6Pe98rbSY", "https://www.ivoox.com/1x04-cosas-como-premios-ig-nobel-especias-y-audios-mp3_rf_61451290_1.html", "1:42:46", "canon");
			Episode episode1x05 = new Episode((byte) 1, (byte) 5, "Cosas como 50 cosas, destrucción de videojuegos y enfermedades mentales", "https://i.ytimg.com/vi/a9z9GfaaXCY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCmkXqiUnX7IbyZKJqomz9H5D6YGw", "https://www.youtube.com/watch?v=a9z9GfaaXCY", "https://www.ivoox.com/1x05-cosas-como-50-cosas-destruccio-769-n-videojuegos-audios-mp3_rf_62632569_1.html", "1:55:36", "canon");
			Episode episode1x06 = new Episode((byte) 1, (byte) 6, "Cosas como Tradiciones navideñas, navidad en las trincheras y el origen de Santa Claus", "https://i.ytimg.com/vi/N2GoaWHuXHo/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBAuSZQN6XLKYZZrCWxj5cYOkATPQ", "https://www.youtube.com/watch?v=N2GoaWHuXHo", "https://www.ivoox.com/1x06-cosas-como-tradiciones-navidenas-navidad-la-audios-mp3_rf_63011219_1.html", "1:34:24", "canon");
			Episode episode1x07 = new Episode((byte) 1, (byte) 7, "Cosas como Cyberpunk 2077, aliens y caballeros", "https://i.ytimg.com/vi/uN0hSOyGCp4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCzWINYSBOFWDRFOYy0JKtnKXd9tw", "https://www.youtube.com/watch?v=uN0hSOyGCp4", "https://www.ivoox.com/1x07-cosas-como-cyberpunk-2077-aliens-caballeros-audios-mp3_rf_63337989_1.html", "1:40:15", "canon");
			Episode episode1x08 = new Episode((byte) 1, (byte) 8, "Cosas como Cosas como Marvel VS DC, memoria y dinero", "https://i.ytimg.com/vi/oOGIiOQXkwI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAO5z5lv9kKKkA-7TN0D-9MK11yXg", "https://www.youtube.com/watch?v=oOGIiOQXkwI", "https://www.ivoox.com/1x08-cosas-como-marvel-vs-dc-memoria-y-audios-mp3_rf_63661225_1.html", "1:57:17", "canon");
			Episode episode1x09 = new Episode((byte) 1, (byte) 9, "Cosas como Wonder Woman 1984, Warhammer 40K y justas", "https://i.ytimg.com/vi/rzfwS6_zTKA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDE_mkxPlsx_PnoUb02wDHCuFpJWw", "https://www.youtube.com/watch?v=rzfwS6_zTKA", "https://www.ivoox.com/1x09-cosas-como-wonder-woman-1984-warhammer-40k-audios-mp3_rf_64016955_1.html", "2:01:32", "canon");
			Episode episode1x10 = new Episode((byte) 1, (byte) 10, "Cosas como Leyendas, secuestro en Moscú y Dios", "https://i.ytimg.com/vi/6tThBmq0vuk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCA6HH-E-j427tNQjQScDepyIkaCQ", "https://www.youtube.com/watch?v=6tThBmq0vuk", "https://www.ivoox.com/1x10-cosas-como-leyendas-secuestro-moscu-y-audios-mp3_rf_64678183_1.html", "1:45:06", "canon");
			Episode episode1x11 = new Episode((byte) 1, (byte) 11, "Cosas como Youtubers y Andorra, 300 y canibalismo", "https://i.ytimg.com/vi/I0JsE5SM--I/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDKhTGbvFHz9-MnzQYjntAI6KB3ww", "https://www.youtube.com/watch?v=I0JsE5SM--I", "https://www.ivoox.com/1x11-cosas-como-youtubers-andorra-300-y-audios-mp3_rf_65037746_1.html", "2:10:00", "canon");
			Episode episode1x12 = new Episode((byte) 1, (byte) 12, "Cosas como La mujer muerta, San Valentín mal y parejas de cine", "https://i.ytimg.com/vi/4e0rEygY4UY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCZw9T-1PpHfkmrY2Bd9NIoQ_msEQ", "https://www.youtube.com/watch?v=4e0rEygY4UY", "https://www.ivoox.com/1x12-cosas-como-la-mujer-muerta-san-valentin-audios-mp3_rf_65409318_1.html", "1:26:14", "canon");
			Episode episode1x13 = new Episode((byte) 1, (byte) 13, "Cosas como fallos en superpoderes, los albores de Youtube y acentos latinos", "https://i.ytimg.com/vi/fKt-aUgWdic/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB_LBQ-m-lDaSEewJZ5IHse-DH5XA", "https://www.youtube.com/watch?v=kVccDLs25mI", "https://www.ivoox.com/1x13-cosas-como-fallos-superpoderes-albores-audios-mp3_rf_65744525_1.html", "1:52:59", "canon");
			Episode episode1x14 = new Episode((byte) 1, (byte) 14, "Cosas como combates imposibles, Perseverance y el tritono del Diablo", "https://i.ytimg.com/vi/kVccDLs25mI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBZ-oM-4hrzUQOBeq4v9KxaFI_y9Q", "https://www.youtube.com/watch?v=fKt-aUgWdic", "https://www.ivoox.com/1x14-cosas-como-combates-imposibles-perseverance-el-audios-mp3_rf_66439947_1.html", "1:54:03", "canon");
			Episode episode1x15 = new Episode((byte) 1, (byte) 15, "Cosas como Bandas sonoras de videojuegos, Bob Dylan y Metal", "https://i.ytimg.com/vi/WGnWbx1qB9g/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCRKvrqd7mo76VaTlStHHd_UBJ9WA", "https://www.youtube.com/watch?v=WGnWbx1qB9g", "https://www.ivoox.com/1x15-cosas-como-bandas-sonoras-videojuegos-bob-audios-mp3_rf_66749709_1.html", "1:42:33", "canon");
			Episode episode1x16 = new Episode((byte) 1, (byte) 16, "Cosas como acertijos, la historia de Twitch y el caso de Elisa Lam", "https://i.ytimg.com/vi/I-hmcSa45w0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBaVX0hLT3GvuYh2L2XFY4oCSgqeA", "https://www.youtube.com/watch?v=I-hmcSa45w0", "https://www.ivoox.com/1x16-cosas-como-acertijos-historia-twitch-audios-mp3_rf_67453168_1.html", "1:58:43", "canon");
			Episode episode1x17 = new Episode((byte) 1, (byte) 17, "Cosas como La liga de la Justicia Snyder cut, dictadores y League of Legends", "https://i.ytimg.com/vi/r_WMkuT87cs/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCs9py4R9CE3tRWkWwqHvrhVw9MWA", "https://www.youtube.com/watch?v=r_WMkuT87cs", "https://www.ivoox.com/1x17-cosas-como-la-liga-justicia-audios-mp3_rf_68381107_1.html", "1:58:09", "canon");
			Episode episode1x18 = new Episode((byte) 1, (byte) 18, "Cosas como The Expanse y la terraformación, baneos en twitch y Remasterizaciones", "https://i.ytimg.com/vi/6Tpm-j386fM/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDfMe_W_QxzdNhlBZ10g9FQs-gBzg", "https://www.youtube.com/watch?v=6Tpm-j386fM", "https://www.ivoox.com/1x18-cosas-como-the-expanse-terraformacion-audios-mp3_rf_69078736_1.html", "1:51:42", "canon");
			Episode episode1x19 = new Episode((byte) 1, (byte) 19, "Cosas como top 10 Youtube, Tarantino y Brandon Lee", "https://i.ytimg.com/vi/vxEGcDcKzOc/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDgQ5Yi2WAsmt1Ag7w2VU85wx5j2g", "https://www.youtube.com/watch?v=vxEGcDcKzOc", "https://www.ivoox.com/1x19-cosas-como-top-10-youtube-tarantino-y-audios-mp3_rf_69370948_1.html", "1:44:39", "canon");
			Episode episode1x20 = new Episode((byte) 1, (byte) 20, "Cosas como top 10 consolas más vendidas, independencia y top animales", "https://i.ytimg.com/vi/dkuErFw5ALI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCz7P6FHAFuj6aYRMQpGOW6mOIlrw", "https://www.youtube.com/watch?v=dkuErFw5ALI", "https://www.ivoox.com/1x20-cosas-como-top-10-consolas-mas-vendidas-audios-mp3_rf_69751352_1.html", "1:53:49", "canon");
			Episode episode1x21 = new Episode((byte) 1, (byte) 21, "Cosas como caracoles, My little pony y El Motín de Esquilache", "https://i.ytimg.com/vi/LBAYhQLycvk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD1yBREifQVZsgRBOFbjnsdc_qEgQ", "https://www.youtube.com/watch?v=LBAYhQLycvk", "https://www.ivoox.com/1x21-cosas-como-caracoles-my-little-pony-y-audios-mp3_rf_70397805_1.html", "1:35:53", "canon");
			Episode episode1x22 = new Episode((byte) 1, (byte) 22, "Cosas como acertijos II, películas mal y top desastres naturales", "https://i.ytimg.com/vi/dBdOWyA07sw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB3QPtcJU5x7pOesf0d7b5vC5uaFg", "https://www.youtube.com/watch?v=dBdOWyA07sw", "https://www.ivoox.com/1x22-cosas-como-acertijos-ii-peliculas-mal-y-audios-mp3_rf_70706166_1.html", "1:49:49", "canon");
			Episode episode1x23 = new Episode((byte) 1, (byte) 23, "Cosas como combates imposibles II, Puente4podcast y quimeras", "https://i.ytimg.com/vi/lfNMPAVUWjk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAhxyqvbxOYBTq6tGm4wbAKUqBG8A", "https://www.youtube.com/watch?v=lfNMPAVUWjk", "https://www.ivoox.com/1x23-cosas-como-combates-imposibles-ii-puente4podcast-y-audios-mp3_rf_71667444_1.html", "2:13:24", "canon");

			Episode episode2x01 = new Episode((byte) 2, (byte) 1, "Cosas como Black Lotus, Pena de Muerte y Leyendas Pokemon: Arceus", "https://i.ytimg.com/an_webp/WhqO4-dJCMc/mqdefault_6s.webp?du=3000&sqp=CNPdiKgG&rs=AOn4CLAx-czD_1Ch5Jn2Z18o0EkK834PPA", "https://www.youtube.com/watch?v=WhqO4-dJCMc&t=3s", "https://www.ivoox.com/2x01-cosas-como-black-lotus-pena-muerte-audios-mp3_rf_75556705_1.html", "2:02:02", "canon");
			Episode episode2x02 = new Episode((byte) 2, (byte) 2, "Cosas como Mundos, Malaz de Steven Erikson y Sumos", "https://i.ytimg.com/an_webp/HaCfSvvcNUU/mqdefault_6s.webp?du=3000&sqp=CMHTiKgG&rs=AOn4CLANV4WgWp6YEggwa4oS0Zo2WD_URg", "https://www.youtube.com/watch?v=HaCfSvvcNUU&t=5390s", "https://www.ivoox.com/2x02-cosas-como-mundos-malaz-steven-erikson-audios-mp3_rf_75823690_1.html", "2:02:02", "canon");
			Episode episode2x03 = new Episode((byte) 2, (byte) 3, "Matrix Resurrections, borramos una saga y Black Alien Project", "https://i.ytimg.com/an_webp/QhAbJfqWtvY/mqdefault_6s.webp?du=3000&sqp=CIjbtqgG&rs=AOn4CLD3wZ-lZG127rLHnlQ5G7LehWOdbQ", "https://www.youtube.com/watch?v=QhAbJfqWtvY&t=4650s", "https://www.ivoox.com/2x03-cosas-como-matrix-resurrections-destruccion-sagas-audios-mp3_rf_76506867_1.html", "2:06:07", "canon");
			Episode episode2x04 = new Episode((byte) 2, (byte) 4, "Netflix y Big Data, Tania Head y Expresiones vol. 2", "https://i.ytimg.com/an_webp/HVRM6SvXhZQ/mqdefault_6s.webp?du=3000&sqp=CJSttqgG&rs=AOn4CLByKNxamHTd6oXErI55yQ75NJ-Yow", "https://www.youtube.com/watch?v=HVRM6SvXhZQ", "https://www.ivoox.com/2x04-cosas-como-netflix-big-data-audios-mp3_rf_76603394_1.html", "2:01:59", "canon");
			Episode episode2x05 = new Episode((byte) 2, (byte) 5, "PODCAST MAL - El podcast de la gente que no sabe de lo que habla", "https://i.ytimg.com/an_webp/z3ZnBXynoCI/mqdefault_6s.webp?du=3000&sqp=CKLJtqgG&rs=AOn4CLC_34NkBSd6c7yFxpIqjsnPWc_8AA", "https://www.youtube.com/watch?v=z3ZnBXynoCI", "https://www.ivoox.com/2x05-cosas-como-podcast-mal-vol-ii-audios-mp3_rf_76944090_1.html", "1:36:11", "canon");
			Episode episode2x06 = new Episode((byte) 2, (byte) 6, "Especial Halloween (Jawelin)", "https://i.ytimg.com/an_webp/y8nN_wRG79I/mqdefault_6s.webp?du=3000&sqp=CIrutqgG&rs=AOn4CLAcaaM-q2OEeg6PiBGDFyVPslKNyg", "https://www.youtube.com/watch?v=y8nN_wRG79I&t=2629s", "https://www.ivoox.com/2x06-cosas-como-especial-halloween-jawelin-audios-mp3_rf_77457287_1.html", "1:50:50", "canon");
			Episode episode2x07 = new Episode((byte) 2, (byte) 7, "IG Nobel Vol II, Gatos Hidráulicos y Pies", "https://i.ytimg.com/an_webp/0wufJwiaVSQ/mqdefault_6s.webp?du=3000&sqp=COjMtqgG&rs=AOn4CLASeAUckL-j62SytD8r_RfLHcd_pQ", "https://www.youtube.com/watch?v=0wufJwiaVSQ", "https://www.ivoox.com/2x07-cosas-como-ig-nobel-vol-ii-gatos-audios-mp3_rf_77762980_1.html", "1:58:38", "canon");
			Episode episode2x08 = new Episode((byte) 2, (byte) 8, "El Elfo Oscuro de R.A. Salvatore, Undertale y el accidente con Alec Baldwin", "https://i.ytimg.com/an_webp/mwqnw6kpLA8/mqdefault_6s.webp?du=3000&sqp=COPktqgG&rs=AOn4CLBaLYupYIfZ6qhxey25C3x5efVBHQ", "https://www.youtube.com/watch?v=mwqnw6kpLA8&t=6180s", "https://www.ivoox.com/2x08-cosas-como-el-elfo-oscuro-r-a-audios-mp3_rf_78080684_1.html", "2:16:56", "canon");
			Episode episode2x09 = new Episode((byte) 2, (byte) 9, "Cuentos Disney originales, Relatos de Terror II, ETERNALS", "https://i.ytimg.com/an_webp/XfRoZQ_fOn8/mqdefault_6s.webp?du=3000&sqp=CLPEtqgG&rs=AOn4CLBWgBVoH-ZyEB7IIcFDpxA4q1tVpQ", "https://www.youtube.com/watch?v=XfRoZQ_fOn8&t=6s", "https://www.ivoox.com/2x09-cosas-como-cuentos-originales-disney-relatos-de-audios-mp3_rf_78562314_1.html", "2:12:23", "canon");
			Episode episode2x10 = new Episode((byte) 2, (byte) 10, "Cosmere.es entrevista - Mistborn, Archivo de las tormentas, Brandon Sanderson", "https://i.ytimg.com/an_webp/uah5vTxNxmY/mqdefault_6s.webp?du=3000&sqp=CMzBtqgG&rs=AOn4CLDyu-rjQcGCaTTpvef1reSQCmJiMg", "https://www.youtube.com/watch?v=uah5vTxNxmY", "https://www.ivoox.com/2x10-cosas-como-cosmere-es-entrevista-audios-mp3_rf_78987418_1.html", "2:27:28", "canon");
			Episode episode2x11 = new Episode((byte) 2, (byte) 11, "Username: Henry - Entrevista Frank Hidalgo-Gato Durán", "https://i.ytimg.com/an_webp/3ixZjta1x-0/mqdefault_6s.webp?du=3000&sqp=CJTltqgG&rs=AOn4CLCKuK8LBcU3cQNOpkVzQYRsffbABg", "https://www.youtube.com/watch?v=3ixZjta1x-0", "https://www.ivoox.com/2x11-cosas-como-entrevista-username-henry-frank-hidalgo-gato-audios-mp3_rf_79812809_1.html", "1:40:28", "canon");
			Episode episode2x12 = new Episode((byte) 2, (byte) 12, "La Fisica del Cosmere, la MODA y Actores de Hollywood", "https://i.ytimg.com/an_webp/a4iKt0n1DYA/mqdefault_6s.webp?du=3000&sqp=CKDttqgG&rs=AOn4CLA5t3IUB8zcknzBgsqMtnaHzW0jEA", "https://www.youtube.com/watch?v=a4iKt0n1DYA", "https://www.ivoox.com/2x12-cosas-como-la-fisica-del-cosmere-la-audios-mp3_rf_81083391_1.html", "1:57:14", "canon");
			Episode episode2x13 = new Episode((byte) 2, (byte) 13, "Fake News, Microsoft compra Activision-Blizzard y El Método Williams", "https://i.ytimg.com/an_webp/Pd9MBe-bK60/mqdefault_6s.webp?du=3000&sqp=CPn7tqgG&rs=AOn4CLDZYKf8H_NXtN0JELtcleCrYtR80g", "https://www.youtube.com/watch?v=Pd9MBe-bK60&t=5604s", "https://www.ivoox.com/2x13-cosas-como-fake-news-microsoft-el-audios-mp3_rf_81711585_1.html", "1:46:06", "canon");
			Episode episode2x14 = new Episode((byte) 2, (byte) 14, "Combates imposibles, Get Back de los Beatles y Meta", "https://i.ytimg.com/an_webp/xQEyQsqzpyk/mqdefault_6s.webp?du=3000&sqp=CO3mtqgG&rs=AOn4CLB3vjRABat1a1drrePkMDwOLaN4lQ", "https://www.youtube.com/watch?v=xQEyQsqzpyk", "https://www.ivoox.com/2x14-cosas-como-combates-imposibles-get-back-de-audios-mp3_rf_82427220_1.html", "2:06:19", "canon");
			Episode episode2x15 = new Episode((byte) 2, (byte) 15, "El Señor de los Anillos: los Anillos de Poder, Relatos de Terror y Reina Roja", "https://i.ytimg.com/an_webp/SyT9e-2tFzU/mqdefault_6s.webp?du=3000&sqp=CNTTtqgG&rs=AOn4CLDzVZeJ3pO2M2yLc5PFK-t3k75how", "https://www.youtube.com/watch?v=SyT9e-2tFzU", "https://www.ivoox.com/2x15-cosas-como-anillos-poder-relatos-audios-mp3_rf_82599675_1.html", "2:03:28", "canon");
			Episode episode2x16 = new Episode((byte) 2, (byte) 16, "A Year of Sanderson - Brandon Sanderson", "https://i.ytimg.com/an_webp/iqyxZk2JS1w/mqdefault_6s.webp?du=3000&sqp=CMzptqgG&rs=AOn4CLBcpwKveWxQu9PC2P30LPMieTq89w", "https://www.youtube.com/watch?v=iqyxZk2JS1w&t=3380s", "https://www.ivoox.com/2x16-cosas-como-a-year-of-sanderson-audios-mp3_rf_83407125_1.html", "1:36:15", "canon");
			Episode episode2x17 = new Episode((byte) 2, (byte) 17, "Archivo de las Tormentas 5 prólogo, Batalla de Stalingrado y Oscars 2022", "https://i.ytimg.com/an_webp/_8AWn6iknV8/mqdefault_6s.webp?du=3000&sqp=CNPjtqgG&rs=AOn4CLBgkPaNLuceCIJ1BKOy9p98M0jXXw", "https://www.youtube.com/watch?v=_8AWn6iknV8&t=7420s", "https://www.ivoox.com/2x17-cosas-como-archivo-tormentas-5-audios-mp3_rf_85052222_1.html", "2:40:33", "canon");
			Episode episode2x18 = new Episode((byte) 2, (byte) 18, "Hogwarts Legacy, cancelan a elxokas, A Los Gatos Ni Tocarlos", "https://i.ytimg.com/an_webp/hbYJOt9I1Hs/mqdefault_6s.webp?du=3000&sqp=CK35tqgG&rs=AOn4CLA5Iw7_KbitTek5Tlcm_rGykOHcVQ", "https://www.youtube.com/watch?v=hbYJOt9I1Hs", "https://www.ivoox.com/2x18-cosas-como-hogwarts-legacy-el-xokas-y-audios-mp3_rf_85419397_1.html", "2:01:58", "canon");
			Episode episode2x19 = new Episode((byte) 2, (byte) 19, "Proyecto Hail Mary de Andy Weir, Relatos de Terror, el Asesino Confeso", "https://i.ytimg.com/an_webp/LuZ2z98vJFM/mqdefault_6s.webp?du=3000&sqp=CNDptqgG&rs=AOn4CLBF5xR3AnHfJ1TK15a8vOcsFG2k3g", "https://www.youtube.com/watch?v=LuZ2z98vJFM", "https://www.ivoox.com/2x19-cosas-como-proyecto-hail-mary-relatos-de-audios-mp3_rf_86345376_1.html", "2:11:55", "canon");
			Episode episode2x20 = new Episode((byte) 2, (byte) 20, "Proyecto Secreto 4 Brandon Sanderson, Kimetsu no Yaiba, afasia de Bruce Willis", "https://i.ytimg.com/an_webp/e0DhVn9L7pQ/mqdefault_6s.webp?du=3000&sqp=CJjitqgG&rs=AOn4CLDGuvBa9UuTuMKNBliAFlljE49KPQ", "https://www.youtube.com/watch?v=e0DhVn9L7pQ&t=3149s", "https://www.ivoox.com/2x20-cosas-como-kimetsu-no-yaiba-4-proyecto-audios-mp3_rf_86455258_1.html", "2:19:11", "canon");
			Episode episode2x21 = new Episode((byte) 2, (byte) 21, "FINAL de Combates Imposibles, Relatos de Terror y La Casa de las Profundidades", "https://i.ytimg.com/an_webp/yCuFrkgnnc4/mqdefault_6s.webp?du=3000&sqp=CNTutqgG&rs=AOn4CLDR9YzFfQhQ7DYvzPFcylzp8HOC4g", "https://www.youtube.com/watch?v=yCuFrkgnnc4&t=2833s", "https://www.ivoox.com/2x21-cosas-como-combates-imposibles-relatos-terror-audios-mp3_rf_87034319_1.html", "2:02:31", "canon");
			Episode episode2x22 = new Episode((byte) 2, (byte) 22, "Vientos de Invierno de G.R.R. Martin, Relatos de Terror, Eurovision 2022", "https://i.ytimg.com/an_webp/qCvks3-htPQ/mqdefault_6s.webp?du=3000&sqp=CNDKtqgG&rs=AOn4CLBrOrilTfgg1-BxnSPQaPDYWoqpKA", "https://www.youtube.com/watch?v=qCvks3-htPQ&t=5683s", "https://www.ivoox.com/2x22-cosas-como-vientos-invierno-rr-audios-mp3_rf_87369239_1.html", "1:51:41", "canon");
			Episode episode2x23 = new Episode((byte) 2, (byte) 23, "Tatuajes, Aquello que Borrarías de la Historia, Aquí no hay quien viva", "https://i.ytimg.com/an_webp/C4lPkFlG244/mqdefault_6s.webp?du=3000&sqp=COLLtqgG&rs=AOn4CLAbWHjiytI4q-aXTM3oOprhUt5DaQ", "https://www.youtube.com/watch?v=C4lPkFlG244&t=5412s", "https://www.ivoox.com/2x23-cosas-como-tatuajes-aquello-borrarias-de-audios-mp3_rf_88048634_1.html", "1:47:57", "canon");
			Episode episode2x24 = new Episode((byte) 2, (byte) 24, "Jurassic Park Saga, Concurso de Relatos y Top Animales Vol 2", "https://i.ytimg.com/an_webp/AmQDeXUY2Dc/mqdefault_6s.webp?du=3000&sqp=CLvHtqgG&rs=AOn4CLBq0_tfveWmvodFCd_-Gm5iSq9xsQ", "https://www.youtube.com/watch?v=AmQDeXUY2Dc", "https://www.ivoox.com/2x24-cosas-como-jurassic-park-fran-green-y-audios-mp3_rf_88303405_1.html", "2:08:01", "canon");
			Episode episode2x25 = new Episode((byte) 2, (byte) 25, "Season Finale Temporada 2", "https://i.ytimg.com/an_webp/KO3Fi40oN8c/mqdefault_6s.webp?du=3000&sqp=CMrytqgG&rs=AOn4CLA4MCLmgx9_jQVmLC5E1RI7JpnJDg", "https://www.youtube.com/watch?v=KO3Fi40oN8c", "https://www.ivoox.com/2x25-cosas-como-season-finale-temporada-2-audios-mp3_rf_88978830_1.html", "1:36:21", "canon");

			Episode episode3x01 = new Episode((byte) 3, (byte) 1, "Los Anillos de Poder, Historia Targaryen y Elden Ring", "https://i.ytimg.com/an_webp/nsOwqK6NvWY/mqdefault_6s.webp?du=3000&sqp=CNj4tqgG&rs=AOn4CLCvWNi9Q1vSh2UAbMnqfEDPKu8gxQ", "https://www.youtube.com/watch?v=nsOwqK6NvWY&t=4686s", "https://www.ivoox.com/3x01-cosas-como-los-anillos-poder-la-audios-mp3_rf_92516350_1.html", "2:25:42", "canon");
			Episode episode3x02 = new Episode((byte) 3, (byte) 2, "Miniaturas de El Archivo de las Tormentas, GTA 6, Origen de frases vol 3", "https://i.ytimg.com/an_webp/iMfp99x0d2o/mqdefault_6s.webp?du=3000&sqp=CPj5tqgG&rs=AOn4CLBXzeVglt7tuuobPrMDDlmoOXAKRA", "https://www.youtube.com/watch?v=iMfp99x0d2o&t=4925s", "https://www.ivoox.com/3x02-cosas-como-miniaturas-brandon-sanderson-gta-audios-mp3_rf_92845201_1.html", "2:06:08", "canon");
			Episode episode3x03 = new Episode((byte) 3, (byte) 3, "Impresiones de Malaz, The Last of Us HBO y Cyberpunk Edgerunners", "https://i.ytimg.com/an_webp/FLhR1vghcks/mqdefault_6s.webp?du=3000&sqp=COjmtqgG&rs=AOn4CLCaF2Ho3qSm2trhernQ5_OHfxOhiw", "https://www.youtube.com/watch?v=FLhR1vghcks&t=949s", "https://www.ivoox.com/3x03-cosas-como-impresiones-malaz-the-last-audios-mp3_rf_93206845_1.html", "1:32:33", "canon");
			Episode episode3x04 = new Episode((byte) 3, (byte) 4, "La Casa del Dragón Vs Los Anillos de Poder, Chainsaw Man, Bombas Atómicas", "https://i.ytimg.com/an_webp/GJ-Q3_zeb0Q/mqdefault_6s.webp?du=3000&sqp=CMTktqgG&rs=AOn4CLDbuzvt3U5-hxmUaHsw2jN-PwZGNg", "https://www.youtube.com/watch?v=GJ-Q3_zeb0Q", "https://www.ivoox.com/3x04-cosas-como-la-casa-del-dragon-vs-audios-mp3_rf_94056346_1.html", "1:57:12", "canon");
			Episode episode3x05 = new Episode((byte) 3, (byte) 5, "Disfraces de Jeffrey Dahmer, sucesos paranormales, videojuegos de terror", "https://i.ytimg.com/an_webp/P68exb_ReI4/mqdefault_6s.webp?du=3000&sqp=CNLrtqgG&rs=AOn4CLCoPFbARP5e-Q5dJPckql4kYg5NCQ", "https://www.youtube.com/watch?v=P68exb_ReI4", "https://www.ivoox.com/3x05-cosas-como-jeffrey-dahmer-historias-paranormales-y-audios-mp3_rf_95072316_1.html", "2:31:19", "canon");
			Episode episode3x06 = new Episode((byte) 3, (byte) 6, "Reparto de Mistborn, proyectos de G.R.R Martin y pantallas de Game Over", "https://i.ytimg.com/an_webp/u7BKvT-BMRA/mqdefault_6s.webp?du=3000&sqp=CODztqgG&rs=AOn4CLB4g4EcFXJHI1ZRPZJpgX98cejI1Q", "https://www.youtube.com/watch?v=u7BKvT-BMRA&t=6767s", "https://www.ivoox.com/3x06-cosas-como-reparto-mistborn-proyectos-de-audios-mp3_rf_96592998_1.html", "2:14:36", "canon");
			Episode episode3x07 = new Episode((byte) 3, (byte) 7, "Reseña sin spoilers de El Metal Perdido, Andor y reset de Los Anillos de Poder", "https://i.ytimg.com/an_webp/P27QabR2V7I/mqdefault_6s.webp?du=3000&sqp=CMjRtqgG&rs=AOn4CLDUg01Mg1_CKYNcJsyr7yQoL3KvVQ", "https://www.youtube.com/watch?v=P27QabR2V7I&t=379s", "https://www.ivoox.com/3x07-cosas-como-el-metal-perdido-andor-y-audios-mp3_rf_97686782_1.html", "1:57:00", "canon");
			Episode episode3x08 = new Episode((byte) 3, (byte) 8, "Combates imposibles, Game Awards 2022, los Sangre Espectral y El Metal Perdido", "https://i.ytimg.com/an_webp/8uIiZQuHNo4/mqdefault_6s.webp?du=3000&sqp=CK7vtqgG&rs=AOn4CLDYuk5r9kfbaxij2hDH8mAisc5b0g", "https://www.youtube.com/watch?v=8uIiZQuHNo4&t=16s", "https://www.ivoox.com/3x08-cosas-como-combates-imposibles-game-awards-2023-audios-mp3_rf_99923973_1.html", "2:16:48", "canon");
			Episode episode3x09 = new Episode((byte) 3, (byte) 9, "Catálogo juguetes 1995, hombres de dorado y rojo en El Metal Perdido, Avatar 2", "https://i.ytimg.com/an_webp/HYBv8W_6NlY/mqdefault_6s.webp?du=3000&sqp=CJzdtqgG&rs=AOn4CLBhjMfcKyBBMZoT613zxSDub5KPMA", "https://www.youtube.com/watch?v=HYBv8W_6NlY", "https://www.ivoox.com/3x09-cosas-como-catalogo-juguetes-1995-hombres-de-audios-mp3_rf_100402075_1.html", "2:39:04", "canon");
			Episode episode3x10 = new Episode((byte) 3, (byte) 10, "PODCAST MAL 3 - El podcast de la gente que no sabe de lo que habla", "https://i.ytimg.com/an_webp/23sHYM4jDx0/mqdefault_6s.webp?du=3000&sqp=CNP5tqgG&rs=AOn4CLCEG5YOKy3NwtUzJ7z9XJoTn85eIQ", "https://www.youtube.com/watch?v=23sHYM4jDx0&t=5s", "https://www.ivoox.com/3x10-cosas-como-el-podcast-mal-3-audios-mp3_rf_100654814_1.html", "1:45:46", "canon");
			Episode episode3x11 = new Episode((byte) 3, (byte) 11, "Combates Imposibles, reseña de Miercoles (Merlina), Henry Cavill y Warhammer", "https://i.ytimg.com/an_webp/tsC5hJjKWAI/mqdefault_6s.webp?du=3000&sqp=CKjitqgG&rs=AOn4CLB2E9wT_Eel7MZByPOmTzHgmn0qug", "https://www.youtube.com/watch?v=tsC5hJjKWAI", "https://www.ivoox.com/3x11-cosas-como-combates-imposibles-miercoles-henry-cavill-audios-mp3_rf_102173093_1.html", "2:25:50", "canon");
			Episode episode3x12 = new Episode((byte) 3, (byte) 12, "Consultorio de la Davidcracia, Esencias del Cosmere, la Ballena Brendan Fraser", "https://i.ytimg.com/an_webp/VJ4PA16g19Y/mqdefault_6s.webp?du=3000&sqp=CLzEtqgG&rs=AOn4CLC7elKEPr5PuYm02pqlCOOSECLoAw", "https://www.youtube.com/watch?v=VJ4PA16g19Y&t=4458s", "https://www.ivoox.com/3x12-cosas-como-el-consultorio-davidcracia-audios-mp3_rf_102945979_1.html", "2:53:41", "canon");
			Episode episode3x13 = new Episode((byte) 3, (byte) 13, "Hogwarts Legacy, Terraplanismo, La Voz de las Espadas de Abercrombie", "https://i.ytimg.com/an_webp/cYN8trONijA/mqdefault_6s.webp?du=3000&sqp=CKD6tqgG&rs=AOn4CLAGbuxIO1FKLet0j5Rs7ItOWfLBGg", "https://www.youtube.com/watch?v=cYN8trONijA&t=489s", "https://www.ivoox.com/3x13-cosas-como-hogwarts-legacy-terraplanismo-joe-audios-mp3_rf_103306614_1.html", "2:00:39", "canon");
			Episode episode3x14 = new Episode((byte) 3, (byte) 14, "Fancast español de Mistborn, Verbolario de R. Cortés, Dogfight Wild Tournament", "https://i.ytimg.com/an_webp/K2qWk1qW3JY/mqdefault_6s.webp?du=3000&sqp=CPrItqgG&rs=AOn4CLDBOfygi2dM71fFAFKamtS-m2AfgA", "https://www.youtube.com/watch?v=K2qWk1qW3JY", "https://www.ivoox.com/3x14-cosas-como-fancast-espanol-mistborn-verbolario-audios-mp3_rf_104077547_1.html", "2:01:08", "canon");
			Episode episode3x15 = new Episode((byte) 3, (byte) 15, "David Hates, Kaladin por The Black Piper, probamos Chat GPT", "https://i.ytimg.com/an_webp/ZvjcDiUmkT0/mqdefault_6s.webp?du=3000&sqp=CIy-tqgG&rs=AOn4CLA60aTmEr4gd_EmXYOFe4NaQdzcWw", "https://www.youtube.com/watch?v=ZvjcDiUmkT0&t=1691s", "https://www.ivoox.com/3x15-cosas-como-david-hates-kaladin-the-black-audios-mp3_rf_105167103_1.html", "1:52:20", "canon");
			Episode episode3x16 = new Episode((byte) 3, (byte) 16, "Revistas Superpop, Cosplay: talyBb, artículo de Jason Kehe", "https://i.ytimg.com/an_webp/ebzMEgavZzM/mqdefault_6s.webp?du=3000&sqp=CNvUtqgG&rs=AOn4CLA8KfnmPmzSOuLgM6896FjDkB8GcQ", "https://www.youtube.com/watch?v=ebzMEgavZzM", "https://www.ivoox.com/3x16-cosas-como-revistas-superpop-talybb-cosplay-jason-audios-mp3_rf_105623293_1.html", "2:16:18", "canon");
			Episode episode3x17 = new Episode((byte) 3, (byte) 17, "El Reboot de Harry Potter, Outside de Brandon Sanderson, reseña: Dungeons & Dragons", "https://i.ytimg.com/an_webp/roAcPJZUjXc/mqdefault_6s.webp?du=3000&sqp=CJXatqgG&rs=AOn4CLDH256Way3g6THTj5D1ZguNWhIwRQ", "https://www.youtube.com/watch?v=roAcPJZUjXc", "https://www.ivoox.com/3x17-cosas-como-reboot-harry-potter-outside-audios-mp3_rf_106430590_1.html", "2:00:38", "canon");
			Episode episode3x18 = new Episode((byte) 3, (byte) 18, "Fan cast español El Archivo de las Tormentas con IA, moda Superpop, saga Zelda", "https://i.ytimg.com/an_webp/Wjb-0BNIvxM/mqdefault_6s.webp?du=3000&sqp=CJ-xtqgG&rs=AOn4CLBRbZLwSmU0c1ORvd1TU6xE3YD4cA", "https://www.youtube.com/watch?v=Wjb-0BNIvxM", "https://www.ivoox.com/3x18-cosas-como-fancast-del-archivo-las-audios-mp3_rf_107625642_1.html", "2:36:29", "canon");
			Episode episode3x19 = new Episode((byte) 3, (byte) 19, "Fan cast El Archivo de las Tormentas con IA, Zelda TOTK, Eurovision 2023", "https://i.ytimg.com/an_webp/baCUb--9c4w/mqdefault_6s.webp?du=3000&sqp=CMj4tqgG&rs=AOn4CLA9uPSonMn8YskxHMF06gxDT9M-pg", "https://www.youtube.com/watch?v=baCUb--9c4w", "https://www.ivoox.com/3x19-cosas-como-fancast-archivo-tormentas-audios-mp3_rf_108515626_1.html", "2:24:33", "canon");
			Episode episode3x20 = new Episode((byte) 3, (byte) 20, "Malaz: Memorias de Hielo, Moldeadores de Alma, nuevo libro de Patrick Rothfuss", "https://i.ytimg.com/an_webp/TWB--TY0x4Q/mqdefault_6s.webp?du=3000&sqp=CPT1tqgG&rs=AOn4CLCUO7JlJ7kzPY6vBplt4LP9OsNY9g", "https://www.youtube.com/watch?v=TWB--TY0x4Q", "https://www.ivoox.com/3x20-cosas-como-malaz-memorias-hielo-moldeadores-audios-mp3_rf_108972596_1.html", "2:05:00", "canon");
			Episode episode3x21 = new Episode((byte) 3, (byte) 21, "Diablo IV, Los Tonos de Roshar con @Pabloglezcas y test de ligue Superpop", "https://i.ytimg.com/an_webp/PBPS_wxWwEk/mqdefault_6s.webp?du=3000&sqp=COHXtqgG&rs=AOn4CLCTNc5VvP7HigSRfejb0jdJtQBLxA", "https://www.youtube.com/watch?v=PBPS_wxWwEk", "https://www.ivoox.com/3x21-cosas-como-diablo-iv-tonos-puros-audios-mp3_rf_110048632_1.html", "2:31:59", "canon");
			Episode episode3x22 = new Episode((byte) 3, (byte) 22, "Combates Imposibles, Starfield, libros de fantasía con Tamara de @Cosmere_es", "https://i.ytimg.com/an_webp/5uAmQrAUq_I/mqdefault_6s.webp?du=3000&sqp=CN7dtqgG&rs=AOn4CLAOBPTZ-Vq6vzr1JkIEJqdxmZeEtw", "https://www.youtube.com/watch?v=5uAmQrAUq_I", "https://www.ivoox.com/3x22-cosas-como-combates-imposibles-starfield-literatura-audios-mp3_rf_110549060_1.html", "2:14:05", "canon");
			Episode episode3x23 = new Episode((byte) 3, (byte) 23, "Season Finale Temporada 3", "https://i.ytimg.com/an_webp/AXDchl0fRHk/mqdefault_6s.webp?du=3000&sqp=CMLKtqgG&rs=AOn4CLD_gY5e3Sx8ZEsaXlN6yE0q-Cj_og", "https://www.youtube.com/watch?v=AXDchl0fRHk", "https://www.ivoox.com/3x23-cosas-como-season-finale-audios-mp3_rf_112042580_1.html", "2:27:27", "canon");

			Archive archivex001 = new Archive((byte) 1, "EL ARCHIVO DE LAS TORMENTAS: RESEÑA BRANDON SANDERSON", "https://i.ytimg.com/vi/qZwE2LDw42E/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLASV5xu-_TjTt0VYh0u-Ih0HI8K9A", "https://www.youtube.com/watch?v=qZwE2LDw42E", "https://www.ivoox.com/arch-1-brandon-sanderson-archivo-de-audios-mp3_rf_62210556_1.html", "2:09:39", "archive");

			List<Season> seasonList = Arrays.asList(season1, season2, season3);
			List<Episode> episodeListS1 = Arrays.asList(episode1x01, episode1x02, episode1x03, episode1x04, episode1x05, episode1x06, episode1x07, episode1x08, episode1x09, episode1x10,
					episode1x11, episode1x12, episode1x13, episode1x14, episode1x15, episode1x16, episode1x17, episode1x18, episode1x19, episode1x20, episode1x21, episode1x22, episode1x23);
			List<Episode> episodeListS2 = Arrays.asList(episode2x01, episode2x02, episode2x03, episode2x04, episode2x05, episode2x06, episode2x07, episode2x08, episode2x09, episode2x10,
					episode2x11, episode2x12, episode2x13, episode2x14, episode2x15, episode2x16, episode2x17, episode2x18, episode2x19, episode2x20, episode2x21, episode2x22, episode2x23,
					episode2x24, episode2x25);
			List<Episode> episodeListS3 = Arrays.asList(episode3x01, episode3x02, episode3x03, episode3x04, episode3x05, episode3x06, episode3x07, episode3x08, episode3x09, episode3x10,
					episode3x11, episode3x12, episode3x13, episode3x14, episode3x15, episode3x16, episode3x17, episode3x18, episode3x19, episode3x20,episode3x21, episode3x22, episode3x23);


			puente4podcast.addPodcastUser(adminUser);
			puente4podcast.addAllSeasons(seasonList);
			puente4podcast.addArchive(archivex001);
			season1.addAllEpisodes(episodeListS1);
			season2.addAllEpisodes(episodeListS2);
			season3.addAllEpisodes(episodeListS3);

			podcastRepository.save(puente4podcast);
			podcastUserRepository.save(adminUser);
			seasonRepository.saveAll(seasonList);
			archiveRepository.save(archivex001);
			episodeRepository.saveAll(episodeListS1);
			episodeRepository.saveAll(episodeListS2);
			episodeRepository.saveAll(episodeListS3);
		};
	}
}