package com.puente4podcast.puente4podcast;

import com.puente4podcast.puente4podcast.models.Episode;
import com.puente4podcast.puente4podcast.models.PodcastUser;
import com.puente4podcast.puente4podcast.repositories.EpisodeRepository;
import com.puente4podcast.puente4podcast.repositories.PodcastUserRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import java.util.Arrays;
import java.util.List;

@SpringBootApplication
public class Puente4podcastApplication {

	public static void main(String[] args) {
		SpringApplication.run(Puente4podcastApplication.class, args);
	}
	@Bean
	public CommandLineRunner initData(PodcastUserRepository podcastUserRepository, EpisodeRepository episodeRepository) {
		return args -> {
			PodcastUser adminUser = new PodcastUser("admin", "admin", "admin", "admin@puente4podcast.com", "chile", "admin");
			podcastUserRepository.save(adminUser);
			Episode episode1x01 = new Episode((byte) 1, (byte) 1, "Cosas como Viajes en el tiempo, Nintendo y experimentos rusos", "https://i.ytimg.com/vi/HCZbEWn328U/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCW9N3Sq2ERk7rNJ6-ZD-koaGSlGg", "https://www.youtube.com/watch?v=HCZbEWn328U", "https://www.ivoox.com/1x01-cosas-como-viajes-tiempo-videojuegos-audios-mp3_rf_60420409_1.html", "1:31:13", "canon");
			Episode episode1x02 = new Episode((byte) 1, (byte) 2, "Cosas como Piratas, tu muerte y Elon Musk", "https://i.ytimg.com/vi/lLdsVHjsQz0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB9glm31mlzCkeTteRxfXe64MHonw", "https://www.youtube.com/watch?v=lLdsVHjsQz0", "https://www.ivoox.com/1x02-cosas-como-piratas-tu-muerte-elon-audios-mp3_rf_60770749_1.html", "1:25:44", "canon");
			Episode episode1x03 = new Episode((byte) 1, (byte) 3, "Cosas como Pelis de libros, parásitos y expresiones", "https://i.ytimg.com/vi/X3ivw_LONtk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDVZJHcDl3BDHXQoHFhBiaZGsxBbQ", "https://www.youtube.com/watch?v=X3ivw_LONtk", "https://www.ivoox.com/1x03-cosas-como-pelis-libros-parasitos-y-audios-mp3_rf_61090555_1.html", "1:35:51", "canon");
			Episode episode1x04 = new Episode((byte) 1, (byte) 4, "Cosas como Premios IgNovel, especias y espadas de videojuegos", "https://i.ytimg.com/vi/kX6Pe98rbSY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC_A67TZ5A1LCW7Fa4rVY8B5quJYQ", "https://www.youtube.com/watch?v=kX6Pe98rbSY", "https://www.ivoox.com/1x04-cosas-como-premios-ig-nobel-especias-y-audios-mp3_rf_61451290_1.html", "1:42:46", "canon");
			Episode episode1x05 = new Episode((byte) 1, (byte) 5, "Cosas como 50 cosas, destrucción de videojuegos y enfermedades mentales", "https://i.ytimg.com/vi/a9z9GfaaXCY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCmkXqiUnX7IbyZKJqomz9H5D6YGw", "https://www.youtube.com/watch?v=a9z9GfaaXCY", "https://www.ivoox.com/1x05-cosas-como-50-cosas-destruccio-769-n-videojuegos-audios-mp3_rf_62632569_1.html", "1:55:36", "canon");
			Episode episode1x06 = new Episode((byte) 1, (byte) 6, "Cosas como Tradiciones navideñas, navidad en las trincheras y el origen de Santa Claus", "https://i.ytimg.com/vi/N2GoaWHuXHo/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBAuSZQN6XLKYZZrCWxj5cYOkATPQ", "https://www.youtube.com/watch?v=N2GoaWHuXHo", "https://www.ivoox.com/1x06-cosas-como-tradiciones-navidenas-navidad-la-audios-mp3_rf_63011219_1.html", "1:34:24", "canon");
			Episode episode1x07 = new Episode((byte) 1, (byte) 7, "Cosas como Cyberpunk 2077, aliens y caballeros", "https://i.ytimg.com/vi/uN0hSOyGCp4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCzWINYSBOFWDRFOYy0JKtnKXd9tw", "https://www.youtube.com/watch?v=uN0hSOyGCp4", "https://www.ivoox.com/1x07-cosas-como-cyberpunk-2077-aliens-caballeros-audios-mp3_rf_63337989_1.html", "1:40:15", "canon");
			Episode episode1x08 = new Episode((byte) 1, (byte) 8, "Cosas como Cosas como Marvel VS DC, memoria y dinero", "https://i.ytimg.com/vi/oOGIiOQXkwI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAO5z5lv9kKKkA-7TN0D-9MK11yXg", "https://www.youtube.com/watch?v=oOGIiOQXkwI", "https://www.ivoox.com/1x08-cosas-como-marvel-vs-dc-memoria-y-audios-mp3_rf_63661225_1.html", "1:57:17", "canon");
			Episode episode1x09 = new Episode((byte) 1, (byte) 9, "Cosas como Wonder Woman 1984, Warhammer 40K y justas", "https://i.ytimg.com/vi/rzfwS6_zTKA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDE_mkxPlsx_PnoUb02wDHCuFpJWw", "https://www.youtube.com/watch?v=rzfwS6_zTKA", "https://www.ivoox.com/1x09-cosas-como-wonder-woman-1984-warhammer-40k-audios-mp3_rf_64016955_1.html", "2:01:32", "canon");
			Episode episode1x10 = new Episode((byte) 1, (byte) 10, "Cosas como Leyendas, secuestro en Moscú y Dios", "https://i.ytimg.com/vi/6tThBmq0vuk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCA6HH-E-j427tNQjQScDepyIkaCQ", "https://www.youtube.com/watch?v=6tThBmq0vuk", "https://www.ivoox.com/1x10-cosas-como-leyendas-secuestro-moscu-y-audios-mp3_rf_64678183_1.html", "1:45:06", "canon");
			Episode episode1x11 = new Episode((byte) 1, (byte) 11, "Cosas como Youtubers y Andorra, 300 y canibalismo", "https://i.ytimg.com/vi/I0JsE5SM--I/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDKhTGbvFHz9-MnzQYjntAI6KB3ww", "https://www.youtube.com/watch?v=I0JsE5SM--I", "https://www.ivoox.com/1x11-cosas-como-youtubers-andorra-300-y-audios-mp3_rf_65037746_1.html", "2:10:00", "canon");
			Episode episode1x12 = new Episode((byte) 1, (byte) 12, "Cosas como La mujer muerta, San Valentín mal y parejas de cine", "https://i.ytimg.com/vi/4e0rEygY4UY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCZw9T-1PpHfkmrY2Bd9NIoQ_msEQ", "https://www.youtube.com/watch?v=4e0rEygY4UY", "https://www.ivoox.com/1x12-cosas-como-la-mujer-muerta-san-valentin-audios-mp3_rf_65409318_1.html", "1:26:14", "canon");
			Episode episode1x13 = new Episode((byte) 1, (byte) 13, "Cosas como fallos en superpoderes, los albores de Youtube y acentos latinos", "https://i.ytimg.com/vi/fKt-aUgWdic/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB_LBQ-m-lDaSEewJZ5IHse-DH5XA", "https://www.youtube.com/watch?v=kVccDLs25mI", "https://www.ivoox.com/1x13-cosas-como-fallos-superpoderes-albores-audios-mp3_rf_65744525_1.html", "1:52:59", "canon");
			Episode episode1x14 = new Episode((byte) 1, (byte) 14, "Cosas como combates imposibles, Perseverance y el tritono del Diablo", "https://i.ytimg.com/vi/kVccDLs25mI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBZ-oM-4hrzUQOBeq4v9KxaFI_y9Q", "https://www.youtube.com/watch?v=fKt-aUgWdic", "https://www.ivoox.com/1x14-cosas-como-combates-imposibles-perseverance-el-audios-mp3_rf_66439947_1.html", "1:54:03", "canon");
			Episode episode1x15 = new Episode((byte) 1, (byte) 15, "Cosas como Bandas sonoras de videojuegos, Bob Dylan y Metal", "https://i.ytimg.com/vi/WGnWbx1qB9g/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCRKvrqd7mo76VaTlStHHd_UBJ9WA", "https://www.youtube.com/watch?v=WGnWbx1qB9g", "https://www.ivoox.com/1x15-cosas-como-bandas-sonoras-videojuegos-bob-audios-mp3_rf_66749709_1.html", "1:42:33", "canon");
			Episode episode1x16 = new Episode((byte) 1, (byte) 16, "Cosas como acertijos, la historia de Twitch y el caso de Elisa Lam", "https://i.ytimg.com/vi/I-hmcSa45w0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBaVX0hLT3GvuYh2L2XFY4oCSgqeA", "https://www.youtube.com/watch?v=I-hmcSa45w0", "https://www.ivoox.com/1x16-cosas-como-acertijos-historia-twitch-audios-mp3_rf_67453168_1.html", "1:58:43", "canon");
			Episode episode1x17 = new Episode((byte) 1, (byte) 17, "Cosas como La liga de la Justicia Snyder cut, dictadores y League of Legends", "https://i.ytimg.com/vi/r_WMkuT87cs/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCs9py4R9CE3tRWkWwqHvrhVw9MWA", "https://www.youtube.com/watch?v=r_WMkuT87cs", "https://www.ivoox.com/1x17-cosas-como-la-liga-justicia-audios-mp3_rf_68381107_1.html", "1:58:09", "canon");
			Episode episode1x18 = new Episode((byte) 1, (byte) 18, "Cosas como The Expanse y la terraformación, baneos en twitch y Remasterizaciones", "https://i.ytimg.com/vi/6Tpm-j386fM/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDfMe_W_QxzdNhlBZ10g9FQs-gBzg", "https://www.youtube.com/watch?v=6Tpm-j386fM", "https://www.ivoox.com/1x18-cosas-como-the-expanse-terraformacion-audios-mp3_rf_69078736_1.html", "1:51:42", "canon");
			Episode episode1x19 = new Episode((byte) 1, (byte) 19, "Cosas como top 10 Youtube, Tarantino y Brandon Lee", "https://i.ytimg.com/vi/vxEGcDcKzOc/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDgQ5Yi2WAsmt1Ag7w2VU85wx5j2g", "https://www.youtube.com/watch?v=vxEGcDcKzOc", "https://www.ivoox.com/1x19-cosas-como-top-10-youtube-tarantino-y-audios-mp3_rf_69370948_1.html", "1:44:39", "canon");
			Episode episode1x20 = new Episode((byte) 1, (byte) 20, "Cosas como top 10 consolas más vendidas, independencia y top animales", "https://i.ytimg.com/vi/dkuErFw5ALI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCz7P6FHAFuj6aYRMQpGOW6mOIlrw", "https://www.youtube.com/watch?v=dkuErFw5ALI", "https://www.ivoox.com/1x20-cosas-como-top-10-consolas-mas-vendidas-audios-mp3_rf_69751352_1.html", "1:53:49", "canon");
			Episode episode1x21 = new Episode((byte) 1, (byte) 21, "Cosas como caracoles, My little pony y El Motín de Esquilache", "https://i.ytimg.com/vi/LBAYhQLycvk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD1yBREifQVZsgRBOFbjnsdc_qEgQ", "https://www.youtube.com/watch?v=LBAYhQLycvk", "https://www.ivoox.com/1x21-cosas-como-caracoles-my-little-pony-y-audios-mp3_rf_70397805_1.html", "1:35:53", "canon");
			Episode episode1x22 = new Episode((byte) 1, (byte) 22, "Cosas como acertijos II, películas mal y top desastres naturales", "https://i.ytimg.com/vi/dBdOWyA07sw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB3QPtcJU5x7pOesf0d7b5vC5uaFg", "https://www.youtube.com/watch?v=dBdOWyA07sw", "https://www.ivoox.com/1x22-cosas-como-acertijos-ii-peliculas-mal-y-audios-mp3_rf_70706166_1.html", "1:49:49", "canon");
			Episode episode1x23 = new Episode((byte) 1, (byte) 23, "Cosas como combates imposibles II, Puente4podcast y quimeras", "https://i.ytimg.com/vi/lfNMPAVUWjk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAhxyqvbxOYBTq6tGm4wbAKUqBG8A", "https://www.youtube.com/watch?v=lfNMPAVUWjk", "https://www.ivoox.com/1x23-cosas-como-combates-imposibles-ii-puente4podcast-y-audios-mp3_rf_71667444_1.html", "2:13:24", "canon");
			List<Episode> season1 = Arrays.asList(episode1x01, episode1x02, episode1x03, episode1x04, episode1x05, episode1x06, episode1x07, episode1x08, episode1x09, episode1x10, episode1x11, episode1x11, episode1x12, episode1x13, episode1x14, episode1x15, episode1x16, episode1x17, episode1x18, episode1x19, episode1x20, episode1x21, episode1x22, episode1x23);
			episodeRepository.saveAll(season1);

			Episode episode2x01 = new Episode((byte) 2, (byte) 1, "Cosas como Black Lotus, Pena de Muerte y Leyendas Pokemon: Arceus", "https://i.ytimg.com/an_webp/WhqO4-dJCMc/mqdefault_6s.webp?du=3000&sqp=CNPdiKgG&rs=AOn4CLAx-czD_1Ch5Jn2Z18o0EkK834PPA", "https://www.youtube.com/watch?v=WhqO4-dJCMc&t=3s", "https://www.ivoox.com/2x01-cosas-como-black-lotus-pena-muerte-audios-mp3_rf_75556705_1.html", "2:02:02", "canon");
			Episode episode2x02 = new Episode((byte) 2, (byte) 2, "Cosas como Mundos, Malaz de Steven Erikson y Sumos", "https://i.ytimg.com/an_webp/HaCfSvvcNUU/mqdefault_6s.webp?du=3000&sqp=CMHTiKgG&rs=AOn4CLANV4WgWp6YEggwa4oS0Zo2WD_URg", "https://www.youtube.com/watch?v=HaCfSvvcNUU&t=5390s", "https://www.ivoox.com/2x02-cosas-como-mundos-malaz-steven-erikson-audios-mp3_rf_75823690_1.html", "2:02:02", "canon");

		};
	}
}