package com.puente4podcast.puente4podcast;
import com.puente4podcast.puente4podcast.models.*;
import com.puente4podcast.puente4podcast.repositories.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
@SpringBootApplication
public class Puente4podcastApplication {
	@Autowired
	private PasswordEncoder passwordEncoder;
	public static void main(String[] args) {
		SpringApplication.run(Puente4podcastApplication.class, args);
	}
	@Bean
	public CommandLineRunner initData(PodcastUserRepository podcastUserRepository, PodcastRepository podcastRepository, SeasonRepository seasonRepository, EpisodeRepository episodeRepository, ArchiveRepository archiveRepository, FavoriteRepository favoriteRepository, ComentaryRepository comentaryRepository) {
		return args -> {

			Podcast puente4podcast = new Podcast("puente4podcast", "El podcast de la gente que ve el mundo, de otra manera!", "https://imgur.com/rJh1nKq");

			PodcastUser adminUser = new PodcastUser("admin", "admin", "admin", "admin@puente4podcast.com", "chile", passwordEncoder.encode("admin"), true, puente4podcast);
			PodcastUser testUser = new PodcastUser("Marco", "Miquel", "NetRunner", "miquel.marco@outlook.com", "chile", passwordEncoder.encode("123"), false, puente4podcast);

			Season season1 = new Season((byte) 1);
			Season season2 = new Season((byte) 2);
			Season season3 = new Season((byte) 3);
			Season season4 = new Season((byte) 4);

			Episode episode1x01 = new Episode((byte) 1, (byte) 1, "Cosas como Viajes en el tiempo, Nintendo y experimentos rusos", "https://i.ytimg.com/vi/HCZbEWn328U/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCW9N3Sq2ERk7rNJ6-ZD-koaGSlGg", "https://www.youtube.com/watch?v=HCZbEWn328U", "https://www.ivoox.com/1x01-cosas-como-viajes-tiempo-videojuegos-audios-mp3_rf_60420409_1.html", "1:31:13", "Canon", "Arrancamos el programa con unos temas bastante interesantes...paradojas temporales, la historia de una de las grandes compañías de videojuevos y un experimento que te pondrá los pelos de punta...", true);
			Episode episode1x02 = new Episode((byte) 1, (byte) 2, "Cosas como Piratas, tu muerte y Elon Musk", "https://i.ytimg.com/vi/lLdsVHjsQz0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB9glm31mlzCkeTteRxfXe64MHonw", "https://www.youtube.com/watch?v=lLdsVHjsQz0", "https://www.ivoox.com/1x02-cosas-como-piratas-tu-muerte-elon-audios-mp3_rf_60770749_1.html", "1:25:44", "Canon","Hablamos sobre un conocido pirata, el futuro día de la muerte de uno de nuestros miembros y de Elon Musk y Neuralink.", true);
			Episode episode1x03 = new Episode((byte) 1, (byte) 3, "Cosas como Pelis de libros, parásitos y expresiones", "https://i.ytimg.com/vi/X3ivw_LONtk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDVZJHcDl3BDHXQoHFhBiaZGsxBbQ", "https://www.youtube.com/watch?v=X3ivw_LONtk", "https://www.ivoox.com/1x03-cosas-como-pelis-libros-parasitos-y-audios-mp3_rf_61090555_1.html", "1:35:51", "Canon", "Esta semana os traemos entre nuestros temas películas basadas en libros, concurso de parásitos y el origen de algunas expresiones que usamos al hablar.", true);
			Episode episode1x04 = new Episode((byte) 1, (byte) 4, "Cosas como Premios IgNovel, especias y espadas de videojuegos", "https://i.ytimg.com/vi/kX6Pe98rbSY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC_A67TZ5A1LCW7Fa4rVY8B5quJYQ", "https://www.youtube.com/watch?v=kX6Pe98rbSY", "https://www.ivoox.com/1x04-cosas-como-premios-ig-nobel-especias-y-audios-mp3_rf_61451290_1.html", "1:42:46", "Canon", "Temas de esta semana: David nos habla sobre los curiosos premios IgNobel, una variante divertida de los Nobel, Sergio nos cuenta la historia de #Magallanes a través de los mares y Roberto nos trae un top con las mejores #espadas de #videjuegos.", true);
			Episode episode1x05 = new Episode((byte) 1, (byte) 5, "Cosas como 50 cosas, destrucción de videojuegos y enfermedades mentales", "https://i.ytimg.com/vi/a9z9GfaaXCY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCmkXqiUnX7IbyZKJqomz9H5D6YGw", "https://www.youtube.com/watch?v=a9z9GfaaXCY", "https://www.ivoox.com/1x05-cosas-como-50-cosas-destruccio-769-n-videojuegos-audios-mp3_rf_62632569_1.html", "1:55:36", "Canon", "David hace un test de preguntas a Sergio y Roberto para conocer un poco más de estos inquietantes sujetos, Sergio nos propone eliminar un videojuego para que nunca haya existido y Roberto nos trae una sección sobre enfermedades mentales.", false);
			Episode episode1x06 = new Episode((byte) 1, (byte) 6, "Cosas como Tradiciones navideñas, navidad en las trincheras y el origen de Santa Claus", "https://i.ytimg.com/vi/N2GoaWHuXHo/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBAuSZQN6XLKYZZrCWxj5cYOkATPQ", "https://www.youtube.com/watch?v=N2GoaWHuXHo", "https://www.ivoox.com/1x06-cosas-como-tradiciones-navidenas-navidad-la-audios-mp3_rf_63011219_1.html", "1:34:24", "Canon", "Hablamos de las tradiciones navideñas en diferentes lugar del mundo, comentamos cómo se vivían la Navidad en las trincheras durante la primera guerra mundial y os contamos el origen de Santa Claus!", false);
			Episode episode1x07 = new Episode((byte) 1, (byte) 7, "Cosas como Cyberpunk 2077, aliens y caballeros", "https://i.ytimg.com/vi/uN0hSOyGCp4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCzWINYSBOFWDRFOYy0JKtnKXd9tw", "https://www.youtube.com/watch?v=uN0hSOyGCp4", "https://www.ivoox.com/1x07-cosas-como-cyberpunk-2077-aliens-caballeros-audios-mp3_rf_63337989_1.html", "1:40:15", "Canon", "Esta semana charlamos del caso de Cyberpunk 2077 y el estado de la industria de los videojuegos, parches del día 1, bugs, DLCs etc. Además exploramos teorías alternativas del origen de la humanidad de la mano de Sergio Monroy, y para acabar, una sección sobre caballeros medievales, explicada por Roberto Álvaro!", false);
			Episode episode1x08 = new Episode((byte) 1, (byte) 8, "Cosas como Cosas como Marvel VS DC, memoria y dinero", "https://i.ytimg.com/vi/oOGIiOQXkwI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAO5z5lv9kKKkA-7TN0D-9MK11yXg", "https://www.youtube.com/watch?v=oOGIiOQXkwI", "https://www.ivoox.com/1x08-cosas-como-marvel-vs-dc-memoria-y-audios-mp3_rf_63661225_1.html", "1:57:17", "Canon", "Debatimos sobre Marvel vs DC (cine) y nos mojamos con cuál nos gusta más, os contamos una inquietante historia, imagínate estar en el metro y no saber quién eres ni cómo has llegado allí... y por último nos salimos un poco de nuestra línea habitual con un encendido debate sobre dinero y políticos!", false);
			Episode episode1x09 = new Episode((byte) 1, (byte) 9, "Cosas como Wonder Woman 1984, Warhammer 40K y justas", "https://i.ytimg.com/vi/rzfwS6_zTKA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDE_mkxPlsx_PnoUb02wDHCuFpJWw", "https://www.youtube.com/watch?v=rzfwS6_zTKA", "https://www.ivoox.com/1x09-cosas-como-wonder-woman-1984-warhammer-40k-audios-mp3_rf_64016955_1.html", "2:01:32", "Canon", "Esta semanita hacemos review de Wonder Woman 1984, y la comparamos con la primera parte, ¿Cuál nos parece mejor? Por otro lado, en la segunda sección vemos el lore detrás de Warhammer 40K, y qué lo hace tan interesante para los fans. Y finalmente, hacemos una justa virtual entre caballeros medievales, ¿Quién ganará?", false);
			Episode episode1x10 = new Episode((byte) 1, (byte) 10, "Cosas como Leyendas, secuestro en Moscú y Dios", "https://i.ytimg.com/vi/6tThBmq0vuk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCA6HH-E-j427tNQjQScDepyIkaCQ", "https://www.youtube.com/watch?v=6tThBmq0vuk", "https://www.ivoox.com/1x10-cosas-como-leyendas-secuestro-moscu-y-audios-mp3_rf_64678183_1.html", "1:45:06", "Canon", "Leyenda de una ciudad castellana muy querida por nosotros, Segovia con su famosa leyenda del acueducto. Por otro lado vemos el secuestro en un teatro de Moscú, Rusia, a manos de unos rebeldes armados de origen checheno, no acaban bien las cosas... Y finalmente, una entretenida sección sobre las 5 vías de santo Tomás de Aquino, que la filosofía nunca pasa de moda!", false);
			Episode episode1x11 = new Episode((byte) 1, (byte) 11, "Cosas como Youtubers y Andorra, 300 y canibalismo", "https://i.ytimg.com/vi/I0JsE5SM--I/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDKhTGbvFHz9-MnzQYjntAI6KB3ww", "https://www.youtube.com/watch?v=I0JsE5SM--I", "https://www.ivoox.com/1x11-cosas-como-youtubers-andorra-300-y-audios-mp3_rf_65037746_1.html", "2:10:00", "Canon", "En la primera sección debatimos sobre el éxodo de algunos youtubers a Andorra a raíz del anuncio de ElRubius. Es legal? Es ético? Hay youtubers que no opinan igual, como Ibai Llanos o ElXokas, anque respeten la decisión. Damos nuestra opinión sin tapujos!. En la segunda parte, nuestro invitado de honor nos habla de incorrecciones en la película 300 basada en la novela gráfica de igual nombre, de Frank Miller. Qué cosas más allá de lo evidente, son veraces en esta grandiosa obra? Lo comentamos en detalle! Y para acabar, una distendida y apetitosa charla sobre canibalismo, para ir abriendo boca!! Ritual? conducta natural? Escúchalo para saberlo!", false);
			Episode episode1x12 = new Episode((byte) 1, (byte) 12, "Cosas como La mujer muerta, San Valentín mal y parejas de cine", "https://i.ytimg.com/vi/4e0rEygY4UY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCZw9T-1PpHfkmrY2Bd9NIoQ_msEQ", "https://www.youtube.com/watch?v=4e0rEygY4UY", "https://www.ivoox.com/1x12-cosas-como-la-mujer-muerta-san-valentin-audios-mp3_rf_65409318_1.html", "1:26:14", "Canon", "Os hablamos de la leyenda de la Mujer Muerta, en la sierra de Guadarrama en la ciudad de Segovia, además os contamos la escalofriante historia de Carl Tanzler, que tenía una visión del romanticismo muy... macabra, os adelanto, que vivía con un cadaver.. Y para acabar, un Top de parejas de cine! Elegimos a las mejores! Y terrible castigo para las perdedoras.", false);
			Episode episode1x13 = new Episode((byte) 1, (byte) 13, "Cosas como fallos en superpoderes, los albores de Youtube y acentos latinos", "https://i.ytimg.com/vi/fKt-aUgWdic/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB_LBQ-m-lDaSEewJZ5IHse-DH5XA", "https://www.youtube.com/watch?v=kVccDLs25mI", "https://www.ivoox.com/1x13-cosas-como-fallos-superpoderes-albores-audios-mp3_rf_65744525_1.html", "1:52:59", "Canon", "Fallos en superpoderes, los poderes de los superheroes de marvel y DC no siempre son muy verosímiles, aquí vemos por qué estos poderes no se podrían dar en la realidad. Poderes de Ant-man, Vision, Cíclope, Superman entre otros! Albores de Youtube, videos y canales míticos de los inicios de Youtube, recuerdas los primeros videos que se hicieron virales? Los repasamos y comentamos, Loulogio, Qué vida más triste etc! Acentos latinos, intentamos acertar (sin mucho éxito) de qué país son sólo por su acento, nos cuesta mucho!", false);
			Episode episode1x14 = new Episode((byte) 1, (byte) 14, "Cosas como combates imposibles, Perseverance y el tritono del Diablo", "https://i.ytimg.com/vi/kVccDLs25mI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBZ-oM-4hrzUQOBeq4v9KxaFI_y9Q", "https://www.youtube.com/watch?v=fKt-aUgWdic", "https://www.ivoox.com/1x14-cosas-como-combates-imposibles-perseverance-el-audios-mp3_rf_66439947_1.html", "1:54:03", "Canon","Por un lado enfrentamos a diferentes personajes de la cultura pop entre ellos, quiién ganaría entre Goku vs Superman? Y entre Iron Man y Batman? Además, charlamos sobre la Perseverance y su reciente llegada a Marte, hablamos sobre sus funciones y la misión que cumple. Y para acabar, conocías el Tritono musical? Te contamos el origen y consecuencias de esta diabólica nota, prohibida en la edad media!", false);
			Episode episode1x15 = new Episode((byte) 1, (byte) 15, "Cosas como Bandas sonoras de videojuegos, Bob Dylan y Metal", "https://i.ytimg.com/vi/WGnWbx1qB9g/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCRKvrqd7mo76VaTlStHHd_UBJ9WA", "https://www.youtube.com/watch?v=WGnWbx1qB9g", "https://www.ivoox.com/1x15-cosas-como-bandas-sonoras-videojuegos-bob-audios-mp3_rf_66749709_1.html", "1:42:33", "Canon", "El podcast de esta semana es musical, os traemos una selección de bandas sonoras de videjuegos, concretamente las que nos han parecido más icónicas. Comentamos las más nostágicas BSOs de videojuegos como Zelda, Tetris, Final Fantasy o Metal Gear entre otras. Por otro lado, os contamos la historia del disco no publicado de Bob Dylan, un disco que se quedo en produción y años después ha sido retomado por diferentes artistas para darle un vuelta y hacer una genial reinterpretación. Y finalmente, nos adentramos en el mundo del metal, para explorar los diferentes géneros del metal que hay, o al menos una selección de ellos, power metal, heavy metal etc. representados por grupos como Sonata Arctica o Craddle of Filth entre otros!", false);
			Episode episode1x16 = new Episode((byte) 1, (byte) 16, "Cosas como acertijos, la historia de Twitch y el caso de Elisa Lam", "https://i.ytimg.com/vi/I-hmcSa45w0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBaVX0hLT3GvuYh2L2XFY4oCSgqeA", "https://www.youtube.com/watch?v=I-hmcSa45w0", "https://www.ivoox.com/1x16-cosas-como-acertijos-historia-twitch-audios-mp3_rf_67453168_1.html", "1:58:43", "Canon", "Acertijos y juego de detectives. Historia de Twitch y curiosidades, su origen y evolución, y también cuál es su funcionamiento. La inquietante historia de Elisa Lam, aprovechando el estreno de su documental en Netflix.", false);
			Episode episode1x17 = new Episode((byte) 1, (byte) 17, "Cosas como La liga de la Justicia Snyder cut, dictadores y League of Legends", "https://i.ytimg.com/vi/r_WMkuT87cs/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCs9py4R9CE3tRWkWwqHvrhVw9MWA", "https://www.youtube.com/watch?v=r_WMkuT87cs", "https://www.ivoox.com/1x17-cosas-como-la-liga-justicia-audios-mp3_rf_68381107_1.html", "1:58:09", "Canon", "Por un lado nuestro análisis de La Liga de la Justicia Snyder Cut, este exitoso estreno de HBO Max, os comentamos nuestra opinión y reseña de la película, sin spoilers! Por otro lado, os traemos una lista con los mayores genocidas de la historia de la humanidad, sabéis cuáles son? Y para acabar, ese amado/odiado juego, el League of Legends, charlamos sobre el LoL y os contamos curiosidades y nuestras experiencias con el juego y su fantástica comunidad.", false);
			Episode episode1x18 = new Episode((byte) 1, (byte) 18, "Cosas como The Expanse y la terraformación, baneos en twitch y Remasterizaciones", "https://i.ytimg.com/vi/6Tpm-j386fM/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDfMe_W_QxzdNhlBZ10g9FQs-gBzg", "https://www.youtube.com/watch?v=6Tpm-j386fM", "https://www.ivoox.com/1x18-cosas-como-the-expanse-terraformacion-audios-mp3_rf_69078736_1.html", "1:51:42", "Canon", "Esta semana hablamos de la serie The Expanse y la terraformación, de la reciente polémica por los baneos en Twitch (el caso de elXokas y Marbella Vice) y acabamos con un debate sobre las remasterizaciones de películas, son necesarias?", false);
			Episode episode1x19 = new Episode((byte) 1, (byte) 19, "Cosas como top 10 Youtube, Tarantino y Brandon Lee", "https://i.ytimg.com/vi/vxEGcDcKzOc/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDgQ5Yi2WAsmt1Ag7w2VU85wx5j2g", "https://www.youtube.com/watch?v=vxEGcDcKzOc", "https://www.ivoox.com/1x19-cosas-como-top-10-youtube-tarantino-y-audios-mp3_rf_69370948_1.html", "1:44:39", "Canon", "- Top 10 videos más vistos de Youtube de la historia. Eliminamos una de las películas de Tarantino, de la mejor a la peor! Historia de Brandon Lee y el rodaje del El Cuervo y su trágica muerte durante el rodaje.", false);
			Episode episode1x20 = new Episode((byte) 1, (byte) 20, "Cosas como top 10 consolas más vendidas, independencia y top animales", "https://i.ytimg.com/vi/dkuErFw5ALI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCz7P6FHAFuj6aYRMQpGOW6mOIlrw", "https://www.youtube.com/watch?v=dkuErFw5ALI", "https://www.ivoox.com/1x20-cosas-como-top-10-consolas-mas-vendidas-audios-mp3_rf_69751352_1.html", "1:53:49", "Canon", "Esta semana en el programa 1x20 del Puente4Podcast, os venimos a hablar sobro el Top 10 de consolas más vendidas de la historia, sabéis cuáles son? Igual hay sorpresa! Por otro lado os contamos cómo un barrio de Madrid, el Cerro Belmonte, declaro unilateralmente la independencia. Pioneros. Para acabar, un concurso en el que intentamos adivinar varios tops de animales, los más rápidos, los más venenosos etc!", false);
			Episode episode1x21 = new Episode((byte) 1, (byte) 21, "Cosas como caracoles, My little pony y El Motín de Esquilache", "https://i.ytimg.com/vi/LBAYhQLycvk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD1yBREifQVZsgRBOFbjnsdc_qEgQ", "https://www.youtube.com/watch?v=LBAYhQLycvk", "https://www.ivoox.com/1x21-cosas-como-caracoles-my-little-pony-y-audios-mp3_rf_70397805_1.html", "1:35:53", "Canon", "Bienvenidos, al Podcast Mal, el podcast de la gente que no sabe de lo que habla. En esta ocasión, literalmente!", false);
			Episode episode1x22 = new Episode((byte) 1, (byte) 22, "Cosas como acertijos II, películas mal y top desastres naturales", "https://i.ytimg.com/vi/dBdOWyA07sw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB3QPtcJU5x7pOesf0d7b5vC5uaFg", "https://www.youtube.com/watch?v=dBdOWyA07sw", "https://www.ivoox.com/1x22-cosas-como-acertijos-ii-peliculas-mal-y-audios-mp3_rf_70706166_1.html", "1:49:49", "Canon", "Esta semana desde el Puente4Podcast os traemos la segunda parte de acertijos (más chungos), también en este programa una nueva sección: Películas mal: Consiste en adivinar una película sabiendo solo una descripción de mierda! Súper divertido!! Y para acabar, la sección del mes elegida por nuestros Patreons con categoría spren: un top de catástrofes naturales!", false);
			Episode episode1x23 = new Episode((byte) 1, (byte) 23, "Cosas como combates imposibles II, Puente4podcast y quimeras", "https://i.ytimg.com/vi/lfNMPAVUWjk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAhxyqvbxOYBTq6tGm4wbAKUqBG8A", "https://www.youtube.com/watch?v=lfNMPAVUWjk", "https://www.ivoox.com/1x23-cosas-como-combates-imposibles-ii-puente4podcast-y-audios-mp3_rf_71667444_1.html", "2:13:24", "Canon", "Para empezar, la segunda parte de la aclamada sección Combates Imposibles!! Esta vez, versión femenina! Continuamos con un making off del Puente4Podcast, os contamos los entresijos del programa, cómo grabamos, curiosidades y sorpresas para la próxima temporada. Y para acabar, una sección sobre quimeras! Es posible hibridar humanos con otras especies? Escúchanos para enterarte!", false);

			Episode episode2x01 = new Episode((byte) 2, (byte) 1, "Cosas como Black Lotus, Pena de Muerte y Leyendas Pokemon: Arceus", "https://i.ytimg.com/vi/WhqO4-dJCMc/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLADMe_3gblZezEV3hdghBFCyUEedw", "https://www.youtube.com/watch?v=WhqO4-dJCMc&t=3s", "https://www.ivoox.com/2x01-cosas-como-black-lotus-pena-muerte-audios-mp3_rf_75556705_1.html", "2:02:02", "Canon", "Y entrando en materia, David nos habla de la carta Black Lotus, de Magic the Gathering la carta más cara de este juego, quieres saber su historia y el porqué de su precio? También repasamos las cartas mas caras de los juegos de mesa! Sergio por su parte, nos trae una recopilación de métodos para ejecutar (nunca mejor dicho) la pena capital, curiosidades y datos reales sobre esta forma de ver la justicia. No te lo pierdas! Y finalmente, de la mano de Rober, damos nuestra opinión sobre el próximo juego de Game Freak, el Pokemon Arceus, vemos el trailer y comentamos nuestras impresiones!!", false);
			Episode episode2x02 = new Episode((byte) 2, (byte) 2, "Cosas como Mundos, Malaz de Steven Erikson y Sumos", "https://i.ytimg.com/vi/HaCfSvvcNUU/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAMuNedmygWqUMoWXWWPd8hGLBLBw", "https://www.youtube.com/watch?v=HaCfSvvcNUU&t=5390s", "https://www.ivoox.com/2x02-cosas-como-mundos-malaz-steven-erikson-audios-mp3_rf_75823690_1.html", "2:02:02", "Canon","- David nos trae una sección en la que nos da  elegir 2 universos de fantasía/literatura, y tenemos que elegir dónde preferiríamos vivir, con sus cosas buenas y malas.. Y vosotros cuál preferís? Sergio viene a hablarnos de cosas como Malaz, la conocida saga de libros de Steven Erikson, realmente le gusta? Nos cuenta su experiencia en la lectura de estos libros. Rober por su parte, nos cuenta la sacrificada vida que llevan los luchadores de sumo, sus tradiciones y curiosidades, conocíais los detalles?", false);
			Episode episode2x03 = new Episode((byte) 2, (byte) 3, "Matrix Resurrections, borramos una saga y Black Alien Project", "https://i.ytimg.com/vi/QhAbJfqWtvY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBxYYMEsbRVwMofzxG2j4PdN0kLBA", "https://www.youtube.com/watch?v=QhAbJfqWtvY&t=4650s", "https://www.ivoox.com/2x03-cosas-como-matrix-resurrections-destruccion-sagas-audios-mp3_rf_76506867_1.html", "2:06:07", "Canon", "David nos trae para comentar el trailer de la cuarta entrega de Matrix: Matrix Resurrections. Vemos el trailer y comentamos lo que nos ha parecido y teorías que circulan por la red, qué opináis? Sergio nos trae un cápitulo más de su sección Aquello que borrarías de la historia, en esta ocasión borramos una saga literaria para que nunca haya existido.. cuál borraríais vosotr@s? Rober nos trae una sección controvertida.. Black Alien Project, si no lo conocéis escuchadnos porque es muy interesante... acaso es un tarado mental? Libertad de expresión con su cuerpo? Debatamos!", false);
			Episode episode2x04 = new Episode((byte) 2, (byte) 4, "Netflix y Big Data, Tania Head y Expresiones vol. 2", "https://i.ytimg.com/vi/HVRM6SvXhZQ/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAV-wKj85hBjHjaAW1_xelI7gSBHw", "https://www.youtube.com/watch?v=HVRM6SvXhZQ", "https://www.ivoox.com/2x04-cosas-como-netflix-big-data-audios-mp3_rf_76603394_1.html", "2:01:59", "Canon", "Netflix y Big Data, nos espían? Cómo usan nuestros datos? Cuánto saben de nosotros? Os lo contamos y opinamos sobre ello! Tania Head, un caso bastante curioso sobre el atentado de las torres gemelas en el 11S, no os lo perdáis porque os va a dejar descolocad@s!! Acabamos con una la segunda parte de una sección divertidísima que trata sobre el origen de expresiones comunes que usamos en el día a día, pero dándoles nuestro toque personal.", false);
			Episode episode2x05 = new Episode((byte) 2, (byte) 5, "PODCAST MAL - El podcast de la gente que no sabe de lo que habla", "https://i.ytimg.com/vi/z3ZnBXynoCI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDrq8zH1iMH38tOUFRKnA869iQH7w", "https://www.youtube.com/watch?v=z3ZnBXynoCI", "https://www.ivoox.com/2x05-cosas-como-podcast-mal-vol-ii-audios-mp3_rf_76944090_1.html", "1:36:11", "Canon", "PODCAST MAL - El podcast de la gente que no sabe de lo que habla 2", false);
			Episode episode2x06 = new Episode((byte) 2, (byte) 6, "Especial Halloween (Jawelin)", "https://i.ytimg.com/vi/y8nN_wRG79I/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLARsBsiYdeZtCcRmbvuvjp8eoFb2A", "https://www.youtube.com/watch?v=y8nN_wRG79I&t=2629s", "https://www.ivoox.com/2x06-cosas-como-especial-halloween-jawelin-audios-mp3_rf_77457287_1.html", "1:50:50", "Canon", "Y hoy.. por Halloween/Día de todos los santos/Día de los muertos.. hemos preparado un programa especial.. un programa que da muchísisismo miedo! Preparaos para hablar de películas de miedo, Jawelin, relatos de terror y engendros salidos del mismísimo averno.", false);
			Episode episode2x07 = new Episode((byte) 2, (byte) 7, "IG Nobel Vol II, Gatos Hidráulicos y Pies", "https://i.ytimg.com/vi/0wufJwiaVSQ/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDBRYe2rWF9eX44ScEBq8u1WuLDwA", "https://www.youtube.com/watch?v=0wufJwiaVSQ", "https://www.ivoox.com/2x07-cosas-como-ig-nobel-vol-ii-gatos-audios-mp3_rf_77762980_1.html", "1:58:38", "Canon", "Por un lado David nos trae más premios IG Nobel, esos premios a estudios absurdos o aparentemente sin sentido. Sergio, nos habla de gatos hidráulicos, pero ojo que viene con sorpresa! Y Rober, en su parte y a petición de los Patreons, nos trae un misterioso caso sin resolver...", false);
			Episode episode2x08 = new Episode((byte) 2, (byte) 8, "El Elfo Oscuro de R.A. Salvatore, Undertale y el accidente con Alec Baldwin", "https://i.ytimg.com/vi/mwqnw6kpLA8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDybP5RmWwdeS7SvR_VYZ9RnMov1w", "https://www.youtube.com/watch?v=mwqnw6kpLA8&t=6180s", "https://www.ivoox.com/2x08-cosas-como-el-elfo-oscuro-r-a-audios-mp3_rf_78080684_1.html", "2:16:56", "Canon", "Para empezar, reseña sin spoilers y recomendación de una de las mejores sagas de fantasía, El Elfo Oscuro de R.A. Salvatore, ambientada en el maravilloso mundo de los Reinos Olvidados (Forgotten Realms) Continuamos con una reseña en profundidad del grandísimo Undertale, ese juego indie que ha conquistado a todo aquel que lo haya jugado! Trama, inicios, BSO comentamos todo! Y para acabar charlamos sobre el desgraciado accidente acontecido durante el rodaje de la última película de Alec Baldwin, evitable? Responsables?", false);
			Episode episode2x09 = new Episode((byte) 2, (byte) 9, "Cuentos Disney originales, Relatos de Terror II, ETERNALS", "https://i.ytimg.com/vi/XfRoZQ_fOn8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD17z8PPEKwVHGHAQgDqXd0HCSl0Q", "https://www.youtube.com/watch?v=XfRoZQ_fOn8&t=6s", "https://www.ivoox.com/2x09-cosas-como-cuentos-originales-disney-relatos-de-audios-mp3_rf_78562314_1.html", "2:12:23", "Canon", "Os contamos los macabros orígenes de los cuentos Disney, escritos muchos de ellos por los hermanos Grimm. Los cuentos de Disney han sido azucarados, pero los cuentos originales de los hermanos Grimm son mucho más oscuros... Adicionalmente, os traemos una nueva dramatización de uno de los relatos que participan en el concurso de relatos de terror que está vigente hasta final de temporada. En esta ocasión es el turno de Mutilado de Panaceo Nivea. ¿Quién se esconde tras este pseudónimo? Y finalmente, una crítica sin spoilers de Eternals, la última película de Marvel. Hacemos una reseña de Eternals y comentamos lo que nos parecen los derroteros que está tomando Marvel con su UCM. ¿A vosotros os ha gustado?", false);
			Episode episode2x10 = new Episode((byte) 2, (byte) 10, "Cosmere.es entrevista - Mistborn, Archivo de las tormentas, Brandon Sanderson", "https://i.ytimg.com/vi/uah5vTxNxmY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDMasaTvr1asfhzPDOegZ-reHKmgQ", "https://www.youtube.com/watch?v=uah5vTxNxmY", "https://www.ivoox.com/2x10-cosas-como-cosmere-es-entrevista-audios-mp3_rf_78987418_1.html", "2:27:28", "Canon", "Programa especial el de este domingo, y como invitados de Honor, contamos con los compañeros de Cosmere.es Ángel y Tamara! Hablamos de cómo surgió su proyecto, cómo fue Brandon Sanderson cuando le conocieron, y aprovechamos para dar un repaso completo al Cosmere. Libros favoritos, personajes, pasajes, TEORÍAS... Comentamos todos los libros del Archivo de las Tormentas, Nacidos de la Bruma (Mistborn), Elantris y el Aliento de los Dioses!!", false);
			Episode episode2x11 = new Episode((byte) 2, (byte) 11, "Username: Henry - Entrevista Frank Hidalgo-Gato Durán", "https://i.ytimg.com/vi/3ixZjta1x-0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDozudWleQBKVnSatsxCaXI1bWZhQ", "https://www.youtube.com/watch?v=3ixZjta1x-0", "https://www.ivoox.com/2x11-cosas-como-entrevista-username-henry-frank-hidalgo-gato-audios-mp3_rf_79812809_1.html", "1:40:28", "Canon", "Esta semana os traemos un programa un poco diferente, en esta ocación entrevistamos al autor de Username: Henry, Frank Hidalgo-Gato Durán. Aprovechamos para comentar el libro, así como qué pasos hay que seguir para publicar un libro, y unos tips sobre como enfocarlo mejor, además hablamos un poco del coste real que suponen este tipo de inversiones. Finalmente, aprovechamos un elemento del libro para abrir un debate sobre scifi, ¿Tomarías una píldora que te hace vivir indefinidamente? ¿Pueden existir las relaciones amorosas con androides?", false);
			Episode episode2x12 = new Episode((byte) 2, (byte) 12, "La Fisica del Cosmere, la MODA y Actores de Hollywood", "https://i.ytimg.com/vi/a4iKt0n1DYA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCsfk1gV84j2IvzJWdzvWtuWM8X9Q", "https://www.youtube.com/watch?v=a4iKt0n1DYA", "https://www.ivoox.com/2x12-cosas-como-la-fisica-del-cosmere-la-audios-mp3_rf_81083391_1.html", "1:57:14", "Canon", "David ha hecho una recopilación del sistema de magias del Cosmere (Roshar en esta ocasión) y nos cuenta en qué fenómenos físicos reales se basan, os suenan las vinculacañas? la luz tormentosa? Os contamos en qué se inspiró Brandon Sanderson para su sistema de magias de El Archivo de las Tormentas! Por otro lado, Sergio nos trae una reseña completa del último disco de la MODA (la Maravillosa Orquesta del Alcohol) este gran grupo castellano, un análisis de el Nuevo Cancionero Burgalés, y comentamos las canciones que más nos han gustado. Y  para acabar, Rober nos trae un listado de 5 actores famosos de Hollywood, y tenemos que hacer un ranking con ellos, sabiendo que el que quede último, muere!!! A quién condenaremos a muerte? Escuchad el programa para saberlo!!", false);
			Episode episode2x13 = new Episode((byte) 2, (byte) 13, "Fake News, Microsoft compra Activision-Blizzard y El Método Williams", "https://i.ytimg.com/vi/Pd9MBe-bK60/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDLu94P2KPoLVc6aPgHUqlUh1oYmw", "https://www.youtube.com/watch?v=Pd9MBe-bK60&t=5604s", "https://www.ivoox.com/2x13-cosas-como-fake-news-microsoft-el-audios-mp3_rf_81711585_1.html", "1:46:06", "Canon", "Esta vez, concurso de cachondeo sobre adivinar fake news, David trae pares de noticias, una falsa y una verdadera, sois capaces de adivinar cuál es la verdadera y cuál la falsa? Echaos unas risas con nosotros! Además, hablamos de la compra de Activision-Blizzard por parte de Microsoft, por una cantidad e dinero obscena, es esto bueno para la industria del videojuego? Se viene oligopolio de ciertas empresas? Y para acabar, reseña de la muy seguramente nóminada a los Oscar, el Método Williams, la última película de Will Smith, que trata sobre la infancia de las hermanas Venus y Serena Williams, y la educación y entrenamiento que recibieron de su padre.", false);
			Episode episode2x14 = new Episode((byte) 2, (byte) 14, "Combates imposibles, Get Back de los Beatles y Meta", "https://i.ytimg.com/vi/xQEyQsqzpyk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCqmmnspjaAFX6S2UYuIjqR-w6p7g", "https://www.youtube.com/watch?v=xQEyQsqzpyk", "https://www.ivoox.com/2x14-cosas-como-combates-imposibles-get-back-de-audios-mp3_rf_82427220_1.html", "2:06:19", "Canon", "Semifinales masculina y femenina de combates imposibles, 16 personajes de ficción se enfrentan en un combate a muerte, quién ganaría? Goku vs Hulk? Yeneffer vs Bella Swan? 8 combates con 16 participantes! Por otro lado Sergio y Adrián nos traen una magnífica máster class sobre los Beatles y su documental Get Back, y si te gusta la música y en especial los Beatles, no te puedes perder su sección de esta semana, curiosidades, anécdotas y muchas cosas más. Para cerrar, Rober nos trae a debate la nueva matriz de Facebook de Mark Zuckerberg, Meta. Comentamos qué nos parece la idea, los pros y contras que le  vemos al Metaverso y si estaríamos dispuesto a usarlo.", false);
			Episode episode2x15 = new Episode((byte) 2, (byte) 15, "El Señor de los Anillos: los Anillos de Poder, Relatos de Terror y Reina Roja", "https://i.ytimg.com/vi/SyT9e-2tFzU/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLADfXqJALE65a5hqptbiwyLEoyVlw", "https://www.youtube.com/watch?v=SyT9e-2tFzU", "https://www.ivoox.com/2x15-cosas-como-anillos-poder-relatos-audios-mp3_rf_82599675_1.html", "2:03:28", "Canon", "Comenzamos nuestras expectativas sobre la nueva serie de Amazon, El Señor de los Anillos: los Anillos de Poder, comentamos el nuevo teaser-trailer de esta prometedora serie, en el que vemos a Galadriel y compañía en esta serie ambientada en su mayoría en la 2ª Edad. Por otro  lado, seguimos con nuestro concurso de relatos, esta vez con 'Lo Desconocido', otra participación que ha sido dramatizada por nuestro compañero Sergio, los pelos como escarpias... Y para acabar, reseña sin spoilers de la novela más vendida en España, Reina Roja de Juan Gómez Jurado, eso sí, con nuestro toque de humor propio.", false);
			Episode episode2x16 = new Episode((byte) 2, (byte) 16, "A Year of Sanderson - Brandon Sanderson", "https://i.ytimg.com/vi/iqyxZk2JS1w/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDIc2Duv7rWPmieeIZxRxmWDh1OXQ", "https://www.youtube.com/watch?v=iqyxZk2JS1w&t=3380s", "https://www.ivoox.com/2x16-cosas-como-a-year-of-sanderson-audios-mp3_rf_83407125_1.html", "1:36:15", "canon", "Con motivo del anuncio de A Year of Sanderson, por parte del propio Brandon Sanderson, hemos decidido dedicar este programa canónico a analizar todos los anuncios que se hicieron la semana pasada. Comentamos los proyectos secretos, el kickstarter, los precios, gastos de envío y diferentes opciones de suscripción del proyecto de Brandon Sanderson llamado A Year of Sanderson. Además, aprovechando la publicación en su página web de los 5 primeros capítulos del Secret Project 1, los comentamos y hacemos un breve análisis de qué podemos esperar de esta novela, y que interconexiones puede tener con el resto del Cosmere.", false);
			Episode episode2x17 = new Episode((byte) 2, (byte) 17, "Archivo de las Tormentas 5 prólogo, Batalla de Stalingrado y Oscars 2022", "https://i.ytimg.com/vi/_8AWn6iknV8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDHhS_gSKKwsfoZIkxhWEoHXyHZ4A", "https://www.youtube.com/watch?v=_8AWn6iknV8&t=7420s", "https://www.ivoox.com/2x17-cosas-como-archivo-tormentas-5-audios-mp3_rf_85052222_1.html", "2:40:33", "Canon", "Para empezar, os contamos la batalla de Stalingrado de la 2ª Guerra Mundial, y hablamos de los paralelismos que hay entre esa masacre, y la guerra actual entre Ucrania y Rusia. Por otro lado, y como no podía ser de otra manera, analizamos escena a escena el recién estrenado prólogo de El Archivo de las Tormentas 5 de Brandon Sanderson. Este hombre nos vuelve a sorprender con un anuncio imprevisto, esta vez sobre El Archivo de las Tormentas (muchos pensábamos que iba a ser algo de Mistborn). Desgranamos todas las teorías que de aquí surgen, de gracias a este gran autor que es Brandon Sanderson. Y para acabar, sección dedicada a los Oscars 2022, hacemos un breve repaso a las películas ganadoras, y por supuesto como no podía ser de otra manera, comentamos la tremenda bofetada de Will Smith a Chris Rock, salseito.", false);
			Episode episode2x18 = new Episode((byte) 2, (byte) 18, "Hogwarts Legacy, cancelan a elxokas, A Los Gatos Ni Tocarlos", "https://i.ytimg.com/vi/hbYJOt9I1Hs/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDaS9M58z9bRDv_Dwc7M52QL1Fvmg", "https://www.youtube.com/watch?v=hbYJOt9I1Hs", "https://www.ivoox.com/2x18-cosas-como-hogwarts-legacy-el-xokas-y-audios-mp3_rf_85419397_1.html", "2:01:58", "Canon", "Por un lado comentamos el nuevo gameplay trailer de Hogwarts Legacy, y hacemos review de lo que nos ha gustado y lo que no! En la siguiente sección, hablamos sobre la reciente funada de elxokas, y su comportamiento de dudosa moralidad, dónde están los límites? Y para acabar Rober nos trae una review del documental de Netflix A Los Gatos Ni Tocarlos, un documental bastante tenso que trata sobre un asesino en serie que subía los videos a internet.", false);
			Episode episode2x19 = new Episode((byte) 2, (byte) 19, "Proyecto Hail Mary de Andy Weir, Relatos de Terror, el Asesino Confeso", "https://i.ytimg.com/vi/LuZ2z98vJFM/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCnWhXZe1UZeAibZRnnF0-8ffJbuQ", "https://www.youtube.com/watch?v=LuZ2z98vJFM", "https://www.ivoox.com/2x19-cosas-como-proyecto-hail-mary-relatos-de-audios-mp3_rf_86345376_1.html", "2:11:55", "Canon", "Reseñamos Proyecto Hail Mary (no spoilers) el último libro de Andy Weir, nuevo relato de nuestro concurso de relatos de terror y os contamos las historia del asesino confeso. Además os traemos un nuevo relato de nuestro concurso de Relatos de Terror, esta vez con una ambientación oscura, y nunca mejor dicho, recordad que podéis participar hasta el 15 de mayo! Y para acabar, nuestra invitada especial y criminóloga de cabecera, nos cuenta la historia del asesino confeso, que según confesó, asesinó a más de 200 personas, quieres saber su historia?", false);
			Episode episode2x20 = new Episode((byte) 2, (byte) 20, "Proyecto Secreto 4 Brandon Sanderson, Kimetsu no Yaiba, afasia de Bruce Willis", "https://i.ytimg.com/vi/e0DhVn9L7pQ/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD1iml5CfqY-mOuGVZd-Umn7ZpfZw", "https://www.youtube.com/watch?v=e0DhVn9L7pQ&t=3149s", "https://www.ivoox.com/2x20-cosas-como-kimetsu-no-yaiba-4-proyecto-audios-mp3_rf_86455258_1.html", "2:19:11", "Canon", "Analizamos en profundidad el Proyecto Secreto 4 de Brandon Sanderson, reseña de la primera temporada de Kimetsu no Yaiba, y hablamos de la afasia de Bruce Willis. Además hacemos un análisis y review de la primera temporada de Kimetsu no Yaiba, comentamos las aventuras de Tanjiro, Nezuko, Zenitsu e Inosuke! Además de la maravillosa factura de animación de Ufotable. Y para acabar, homenajeamos la carrera de Bruce Willis haciendo un repaso de toda su filmografía, comentando su triste enfermedad y su retiro, así como las películas que más nos han gustado.", false);
			Episode episode2x21 = new Episode((byte) 2, (byte) 21, "FINAL de Combates Imposibles, Relatos de Terror y La Casa de las Profundidades", "https://i.ytimg.com/vi/yCuFrkgnnc4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD0RQUkcLUSGTvgdUxEUONGohLp2Q", "https://www.youtube.com/watch?v=yCuFrkgnnc4&t=2833s", "https://www.ivoox.com/2x21-cosas-como-combates-imposibles-relatos-terror-audios-mp3_rf_87034319_1.html", "2:02:31", "canon", "Y no faltamos a nuestra cita semanal con 3 nuevos temitas! Esta vez os traemos las final de combates imposibles, es Goku invencible? Déjanos tu opinión! Además el penúltimo relato del nuestro concurso de relatos de terror hoy era el último día para participar, así que están cerradas las solicitudes! Welcome to the Puente4Podcast-verse. Y para acabar, os traemos una reseña SIN SPOILERS de la original película de terror La Casa de las Profundidades!! Os atrevéis?", false);
			Episode episode2x22 = new Episode((byte) 2, (byte) 22, "Vientos de Invierno de G.R.R. Martin, Relatos de Terror, Eurovision 2022", "https://i.ytimg.com/vi/qCvks3-htPQ/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAnGwk8uD1nE2d-thQZxqSqQf532w", "https://www.youtube.com/watch?v=qCvks3-htPQ&t=5683s", "https://www.ivoox.com/2x22-cosas-como-vientos-invierno-rr-audios-mp3_rf_87369239_1.html", "1:51:41", "Canon", "Si como nosotros estáis esperando desde hace 10 años el sexto libro de G.R.R. Martin titulado Vientos de Invierno, nos os perdáis la primera sección la que debatimos y damos nuestra opinión sobre la tardanza de este libro de la saga Canción de Hielo y Fuego (Juego de Tronos), comentamos qué ha estado haciendo Martin estos últimos años, además de 'escribir' el libro. Por otro lado os traemos el último relato participante en nuestro concurso de relatos, recordad que podéis volverlos a escuchar en nuestros videos y están disponibles en nuestro Discord! Y para acabar comentamos la gala de Eurovision 2022, las actuaciones que más nos han gustado, las que menos, quién queríamos que ganase y por supuesto qué nos pareció la actuación de la representante español Chanel, con su Slomo.", false);
			Episode episode2x23 = new Episode((byte) 2, (byte) 23, "Tatuajes, Aquello que Borrarías de la Historia, Aquí no hay quien viva", "https://i.ytimg.com/vi/C4lPkFlG244/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBEHhbxIHl5Go5cIO_302OYxSu2Cw", "https://www.youtube.com/watch?v=C4lPkFlG244&t=5412s", "https://www.ivoox.com/2x23-cosas-como-tatuajes-aquello-borrarias-de-audios-mp3_rf_88048634_1.html", "1:47:57", "Canon", "Hoy David, con su tatuaje gallinil recién hecho, nos comenta los diferentes estilos de tatuaje! Y de paso, charlamos sobre los diferentes tatus que tenemos, fuah! Por otro lado gente, Sergio nos trae otra edición de Aquello que borrarías de la Historia! Eso es gente habéis oído bien! Una sección bien chidori para que os lo paséis bien padrísimo! Y para acabar, la sección de Rober trata de Aquí no hay quien viva! Un nuevo concurso entre nosotros sobre esta serie! O venía a contaros curiosidades? No lo sé, como no me he leído la circular.. :D", false);
			Episode episode2x24 = new Episode((byte) 2, (byte) 24, "Jurassic Park Saga, Concurso de Relatos y Top Animales Vol 2", "https://i.ytimg.com/vi/AmQDeXUY2Dc/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLABuMmsYCrfK8yD905sZrHO5q-E3A", "https://www.youtube.com/watch?v=AmQDeXUY2Dc", "https://www.ivoox.com/2x24-cosas-como-jurassic-park-fran-green-y-audios-mp3_rf_88303405_1.html", "2:08:01", "Canon", "Esta semana os traemos un debate sobre Jurassic Park, y repasamos todas las películas de cara al estreno de la última entrega Jurassic Park Dominion, a vosotr@s también os encanta esta saga de Steven Spielberg? En la segunda sección invitamos al ganador del concurso de relatos de terror de Puente4Podscast, Fran Green, nos comenta cómo fue su proceso creativo y las ideas que le llevaron a escribir el relato ganador. Y para acabar, otro divertido quiz sobre un Top de animales, cuáles son los más listos? los que más viven o los que más matan? No os lo perdáis!", false);
			Episode episode2x25 = new Episode((byte) 2, (byte) 25, "Season Finale Temporada 2", "https://i.ytimg.com/vi/KO3Fi40oN8c/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB46yJZvBBaNp8GwwnEUlMuA9Zl6A", "https://www.youtube.com/watch?v=KO3Fi40oN8c", "https://www.ivoox.com/2x25-cosas-como-season-finale-temporada-2-audios-mp3_rf_88978830_1.html", "1:36:21", "Canon", "Otro año más, y otra temporada más de nuestro podcast, y para finalizar os traemos un Season Finale de la segunda temporada! Comentamos el año, lo que más nos ha gustado, las expectativas que teníamos y si se han cumplido o no, además comentamos varias ideas y proyectos que tenemos para la temporada 3, porque esto no se acaba!!!", false);

			Episode episode3x01 = new Episode((byte) 3, (byte) 1, "Los Anillos de Poder, Historia Targaryen y Elden Ring", "https://i.ytimg.com/vi/nsOwqK6NvWY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCL1qgYJKtSTpz2USEq0kpPtXcJYw", "https://www.youtube.com/watch?v=nsOwqK6NvWY&t=4686s", "https://www.ivoox.com/3x01-cosas-como-los-anillos-poder-la-audios-mp3_rf_92516350_1.html", "2:25:42", "Canon", "Primeras impresiones y análisis de Los Anillos de Poder, la nueva serie ambientada en el universo de El Señor de los Anillos de Tolkien, en el que seguiremos las aventuras de Galadriel, os contamos qué nos ha parecido, que no nos ha gustado y comentamos la polémicas que hay en torno a Los Anillos de Poder, serie de Amazon Prime Video. La historia de la Casa Targaryen, de la mano de Sergio, nos adentramos en la genealogía de esta antigua casa, todo lo que necesitas saber del lore para entender la serie de HBO La Casa del Dragón basada en el texto de G.R.R. Martin Fuego y Sangre. No te pierdas la historia de los Targaryen!  Para acabar, Rober nos cuenta su experiencia con Elden Ring, el útlimo juego souls like de FromSoftware, qué le habrá parecido? Es difícil? Analizamos las carencias y virtudes de este juego, así que si eres un fan de los Dark Souls o del Elden Ring, este análisis te va a interesar!", false);
			Episode episode3x02 = new Episode((byte) 3, (byte) 2, "Miniaturas de El Archivo de las Tormentas, GTA 6, Origen de frases vol 3", "https://i.ytimg.com/vi/iMfp99x0d2o/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLArhgVUSaop5_fCIr7_fq4HuvSNAA", "https://www.youtube.com/watch?v=iMfp99x0d2o&t=4925s", "https://www.ivoox.com/3x02-cosas-como-miniaturas-brandon-sanderson-gta-audios-mp3_rf_92845201_1.html", "2:06:08", "Canon", "Por un lado te contamos todo lo que necesitas saber de las miniaturas de El Archivo de las Tormentas de Brandon Sanderso. El proyecto en kickstarter, precios, qué incluye, gastos de envío.. una guia de compra del Cosmere! Por otro lado comentamos la reciente filtración del GTA VI de Rockstar Games. Tras el reciente hackeo se han hecho públicos varios videos del Grand Theft Auto VI, confirmados por la propia Rockstar, os lo contamos todo. Y para acabar, volvemos con la tercera parte del origen de frases que usamos en el día a día! Muy curiosas!", false);
			Episode episode3x03 = new Episode((byte) 3, (byte) 3, "Impresiones de Malaz, The Last of Us HBO y Cyberpunk Edgerunners", "https://i.ytimg.com/vi/FLhR1vghcks/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDtOi_OlQLhOaOOw1ub_k0oJFXz_g", "https://www.youtube.com/watch?v=FLhR1vghcks&t=949s", "https://www.ivoox.com/3x03-cosas-como-impresiones-malaz-the-last-audios-mp3_rf_93206845_1.html", "1:32:33", "Canon", "Primeras impresiones de la Davidcracia al llegar al 50% de Los Jardines de la Luna, el primer libro de Malaz de Steven Eriskon, le estará gustando? O será un pozo de hate? Todo lo que sabemos sobre la nueva serie de HBO, The Last of Us! Comentamos el trailer, trama, elenco de actores y similitudes con el juego de que se ha mostrado hasta ahora. Para acabar, recomendación de la barbaridad de serie que es Cyberpunk Edgerunners de Netflix, ambientada en el mismo universo que Cyberpunk 2077, el juego de CD Projekt!!", false);
			Episode episode3x04 = new Episode((byte) 3, (byte) 4, "La Casa del Dragón Vs Los Anillos de Poder, Chainsaw Man, Bombas Atómicas", "https://i.ytimg.com/vi/GJ-Q3_zeb0Q/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCEqHbaqW8pwtiuf0WgPpUgAB7W0g", "https://www.youtube.com/watch?v=GJ-Q3_zeb0Q", "https://www.ivoox.com/3x04-cosas-como-la-casa-del-dragon-vs-audios-mp3_rf_94056346_1.html", "1:57:12", "Canon", "¿Por qué La Casa del Dragón es mejor que Los Anillos de Poder? ¿Qué está haciendo mejor HBO que Amazon? Hablamos de Chainsaw Man y su estreno en versión anime, ¿Habéis leído este manga de Tatsuki Fujimoto y adaptado por Mappa? Para acabar, charlamos sobre los diferentes tipos de bombas atómicas que hay, y sus diferentes potencias.", false);
			Episode episode3x05 = new Episode((byte) 3, (byte) 5, "Disfraces de Jeffrey Dahmer, sucesos paranormales, videojuegos de terror", "https://i.ytimg.com/vi/P68exb_ReI4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA-D_OVUCf9hX_EBLZR5lEBan4Ucg", "https://www.youtube.com/watch?v=P68exb_ReI4", "https://www.ivoox.com/3x05-cosas-como-jeffrey-dahmer-historias-paranormales-y-audios-mp3_rf_95072316_1.html", "2:31:19", "Canon", "La polémica surgida en torno a los disfraces de Jeffrey Dahmer, a raíz de la serie Dahmer de Netflix, es lícito disfrazarse de un asesino en serie? Dónde están los límites? Por otro lado comentamos las historias paranormales que nos habéis mandado con motivo de Halloween, muuuy terroríficas. Y para acabar hacemos un repaso cronológico por los videojuegos de terror que más nos han gustado! Resident Evil, Silent Hill, Dead Space y muchos otros!", false);
			Episode episode3x06 = new Episode((byte) 3, (byte) 6, "Reparto de Mistborn, proyectos de G.R.R Martin y pantallas de Game Over", "https://i.ytimg.com/vi/u7BKvT-BMRA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCAFNK-RBBipWEnDkc2ozshSRySvw", "https://www.youtube.com/watch?v=u7BKvT-BMRA&t=6767s", "https://www.ivoox.com/3x06-cosas-como-reparto-mistborn-proyectos-de-audios-mp3_rf_96592998_1.html", "2:14:36", "Canon", "Y otro domingo más para no faltar a la costumbre os traemos temas muy fresquitos! Esta semana os hablamos del que nos gustaría que fuese el casting del la posible pelicula de Mistborn (Nacidos de la Bruma) de Brandon Sanderson, quién podría ser Kelsier, Vin el Lord Legislador o Sazed? Además hacemos un repaso a todos los proyectos pendientes de G.R.R. Martin, incluyendo por supuesto Vientos de Invierno o Sueño de Primavera así como las series pendientes por salir como la de Nymeria o Jon Nieve, después del éxito de la Casa del Dragón. Para acabar, nuestro invitado especial Gabriel, viene a hablarnos de cosas como las pantallas de Game Over de los videojuegos, y las músicas que suenan cuando morimos en nuestras partidas.", false);
			Episode episode3x07 = new Episode((byte) 3, (byte) 7, "Reseña sin spoilers de El Metal Perdido, Andor y reset de Los Anillos de Poder", "https://i.ytimg.com/vi/P27QabR2V7I/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBb1Xo4okLHiY4oB4FRGPKz6BCVaw", "https://www.youtube.com/watch?v=P27QabR2V7I&t=379s", "https://www.ivoox.com/3x07-cosas-como-el-metal-perdido-andor-y-audios-mp3_rf_97686782_1.html", "1:57:00", "Canon", "Hacemos una reseña sin spoilers del último libro de Brandon Sanderson, El Metal Perdido, el final de era 2 de Mistborn, que pon cierre a este arco de Nacidos de la bruma, comentamos las aventuras de Wax, Wayne y compañía! Además Sergio nos trae una recomendación de Star Wars, y se trata nada más y nada menos que de la nueva serie Andor, basada en el universo de la Guerra de las Galaxias, os contamos si merece la pena verla y a quién va dirigida, buen análisis! Y finalmente charlamos sobre el posible resteo de Los Anillos de Poder, la serie de El Señor de Anillos de Amazon Prime, que se ha llevado duros palos tras su estreno por ser una paupérrima adaptación del universo de Tolkien, en la Segunda temporada de los Anillos de Poder harán un reset? Lo comentamos!", false);
			Episode episode3x08 = new Episode((byte) 3, (byte) 8, "Combates imposibles, Game Awards 2022, los Sangre Espectral y El Metal Perdido", "https://i.ytimg.com/vi/8uIiZQuHNo4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAEvboGGSk2OWYXyttpeDO4pPTvHg", "https://www.youtube.com/watch?v=8uIiZQuHNo4&t=16s", "https://www.ivoox.com/3x08-cosas-como-combates-imposibles-game-awards-2023-audios-mp3_rf_99923973_1.html", "2:16:48", "Canon", "Esta semana os traemos una nueva edición de combates imposibles, quienes serán los contendientes esta vez? Si os gustaron las ediciones anteriores, está seguro que os encanta!! Además, hacemos un repaso a la los Game Awards 2022, los prestigiosos premios de videojuegos, comentamos los galardonados y cuál ha sido el GOTY de este año, buena charla! Y para acabar, os traemos  más contenido desgranado y explicado del El Metal Perdido de Brandon Sanderson, concretamente está vez hablamos de los Sangre Espectral, todo lo que necesitas saber de este peligroso grupo, pero esta vez, en la saga Mistborn (Nacidos de la Bruma) de Brandon Sanderson!! Si te gustó nuestro programa de El Metal Perdido, este seguro que te encanta!", false);
			Episode episode3x09 = new Episode((byte) 3, (byte) 9, "Catálogo juguetes 1995, hombres de dorado y rojo en El Metal Perdido, Avatar 2", "https://i.ytimg.com/vi/HYBv8W_6NlY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDTFuDrVLuINnUdaWwooP-FTN2Mdg", "https://www.youtube.com/watch?v=HYBv8W_6NlY", "https://www.ivoox.com/3x09-cosas-como-catalogo-juguetes-1995-hombres-de-audios-mp3_rf_100402075_1.html", "2:39:04", "Canon", "Comentamos un catálogo de juguetes de 1995, y vemos las diferencias que hay con los de ahora, además de comentar con nostalgia los juguetes de nuestra infancia. Por otro lado, os traemos toda la información que hay hasta la fecha de los hombres de dorado y rojo que aparecen en El Metal Perdido, quiénes son y de dónde vienen, teorías de dónde pueden proceder y cuáles son sus intereses, teorías bien ricas del Cosmere de Brandon Sanderson! Y para acabar, análisis de Avatar 2 el Sentido del Agua, de James Cameron, la esperada secuela de Avatar, que lleva en desarrollo la friolera de 13 años. Ya está estrenada y os contamos sin spoilers lo que nos ha parecido Avatar 2.", false);
			Episode episode3x10 = new Episode((byte) 3, (byte) 10, "PODCAST MAL 3 - El podcast de la gente que no sabe de lo que habla", "https://i.ytimg.com/vi/23sHYM4jDx0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBsMiyIxRr-n927ndAzmcxwryV8Gw", "https://www.youtube.com/watch?v=23sHYM4jDx0&t=5s", "https://www.ivoox.com/3x10-cosas-como-el-podcast-mal-3-audios-mp3_rf_100654814_1.html", "1:45:46", "Canon", "Una nueva edición del Pocast Mal, un programa perpetrado por Puente4Podcast, tan intensamente malo, que nos vemos obligados a limitarlo a 1 vez por temporada.", false);
			Episode episode3x11 = new Episode((byte) 3, (byte) 11, "Combates Imposibles, reseña de Miercoles (Merlina), Henry Cavill y Warhammer", "https://i.ytimg.com/vi/tsC5hJjKWAI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCUrDPddA06HWS3RSZsEHICpisV-A", "https://www.youtube.com/watch?v=tsC5hJjKWAI", "https://www.ivoox.com/3x11-cosas-como-combates-imposibles-miercoles-henry-cavill-audios-mp3_rf_102173093_1.html", "2:25:50", "Canon", "Hacemos una nueva ronda de Combates Imposibles, tras la última velada, quiénes son los contendientes que pasarán a la semifinal? Además, hacemos análisis y reseña con spoilers de Miércoles (Merlina) la nueva serie de Tim Burton que se emite en Netlix y que ha tenido un gran éxito, protagonizada por Jenna Ortega, y basada en la Familia Addams. Para acabar, comentamos el futuro de Warhammer, y los proyectos que tiene Henry Cavill tras abandonar el proyecto de The Witcher. Todo lo que sabemos de este nuevo proyecto de WH40K.", false);
			Episode episode3x12 = new Episode((byte) 3, (byte) 12, "Consultorio de la Davidcracia, Esencias del Cosmere, la Ballena Brendan Fraser", "https://i.ytimg.com/vi/VJ4PA16g19Y/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBJ2ypYqeOGahls3wM-4esVzHeiCg", "https://www.youtube.com/watch?v=VJ4PA16g19Y&t=4458s", "https://www.ivoox.com/3x12-cosas-como-el-consultorio-davidcracia-audios-mp3_rf_102945979_1.html", "2:53:41", "Canon", "Una semana más acudimos puntuales a nuestra cita, y en esta ocasión os traemos el aclamado Consultorio de la Davidcracia, en donde respondemos a dudas y consultas realizadas por vosotros!! Por otro lado, os traemos una didáctica sección sección con las Esencias del Cosmere, y sus relaciones con las esporas de Trenza del Mar Esmeralda, o Roshar en el Archivo de las Tormentas, así como en Mistborn (Nacidos de la Bruma) de Brandon Sanderson. Y para acabar, una pequeña review SIN SPOILERS de la última película de Brendan Frase, La Ballena. Que se postula como firme candidata a los premios Oscar del 2023.", false);
			Episode episode3x13 = new Episode((byte) 3, (byte) 13, "Hogwarts Legacy, Terraplanismo, La Voz de las Espadas de Abercrombie", "https://i.ytimg.com/vi/cYN8trONijA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCyra94fRPHYuv8FSamsFC_8zqjBw", "https://www.youtube.com/watch?v=cYN8trONijA&t=489s", "https://www.ivoox.com/3x13-cosas-como-hogwarts-legacy-terraplanismo-joe-audios-mp3_rf_103306614_1.html", "2:00:39", "Canon", "Por un lado os comentamos lo que nos está pareciendo Hogwarts Legacy en lo que llevamos jugado, merece la pena? Es un videojuego fanservice? Además, hablamos sobre USA el terraplanismo y las carreteras! Tema interesante!! Y para acabar, reseña de la Voz de las Espadas de Joe Abercrombie (sin spoilers), cometamos lo que nos parece este primer libro de la famosa saga La Primera Ley, una aventura grim dark que teníamos pendiente!", false);
			Episode episode3x14 = new Episode((byte) 3, (byte) 14, "Fancast español de Mistborn, Verbolario de R. Cortés, Dogfight Wild Tournament", "https://i.ytimg.com/vi/K2qWk1qW3JY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCn9v5DMtsGLd2Umw9HRnG4bM7OYw", "https://www.youtube.com/watch?v=K2qWk1qW3JY", "https://www.ivoox.com/3x14-cosas-como-fancast-espanol-mistborn-verbolario-audios-mp3_rf_104077547_1.html", "2:01:08", "Canon", "Programa fresquito, acorde a las temperaturas! Os tramos la segunda edición del reparto de mistborn, pero esta vez con actores y actrices españoles/as! A quién pondriais vosotr@s si la adaptación de Mistborn (Nacidos de la Bruma) de Brandon Sanderson fuese una  película española? Os lo desvelamos! Además comentamos el libro Verbolario de Rodrigo Cortés, un libro muy original a modo de diccionario que desnuda las palabras para darnos un significado que te dará qué pensar. Y finalmente comentamos el Dogfight Wild Tournament de Jordi Wild, en cuya velada hubo un montón de combates de MMA y boxeos, entre otras cosas! Si os molan los deportes de contacto os gustará esta sección!", false);
			Episode episode3x15 = new Episode((byte) 3, (byte) 15, "David Hates, Kaladin por The Black Piper, probamos Chat GPT", "https://i.ytimg.com/vi/ZvjcDiUmkT0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBr6CaSiWte3U_c_VVdCw7U2e5VsA", "https://www.youtube.com/watch?v=ZvjcDiUmkT0&t=1691s", "https://www.ivoox.com/3x15-cosas-como-david-hates-kaladin-the-black-audios-mp3_rf_105167103_1.html", "1:52:20", "Canon", "Y finalmente comentamos el Dogfight Wild Tournament de Jordi Wild, en cuya velada hubo un montón de combates de MMA y boxeos, entre otras cosas! Si os molan los deportes de contacto os gustará esta sección! En segundo lugar, os traemos la recomendación del álbum Kaladin de The Black Piper. Si eres fanático de la fantasía, este álbum es para ti. Está inspirado en la serie de libros El Archivo de las Tormentas de Brandon Sanderson y tiene una música épica que te llevará directo al Cosmere Finalmente, vamos a probar Chat GPT. Es una tecnología muy interesante que utiliza inteligencia artificial para responder preguntas y generar texto de manera natural. En este video, haremos algunas pruebas para ver cómo funciona y si es útil, e intentaremos crear el himno de la Davidcracia.", false);
			Episode episode3x16 = new Episode((byte) 3, (byte) 16, "Revistas Superpop, Cosplay: talyBb, artículo de Jason Kehe", "https://i.ytimg.com/vi/ebzMEgavZzM/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCt6f71uzkbrIm66q8aBUghFsIjUw", "https://www.youtube.com/watch?v=ebzMEgavZzM", "https://www.ivoox.com/3x16-cosas-como-revistas-superpop-talybb-cosplay-jason-audios-mp3_rf_105623293_1.html", "2:16:18", "Canon", "Esta semana os traemos temas interesantes como por ejemplo, comentamos las portadas de la mítica revista Superpop, pura nostalgia Millenial, recordáis estas revistas? No tienen desperdicio! Por otro lado, contamos con una magnífica invitada de honor, la cosplayer de élite talyBb, que ha trabajado junto a empresas como Blizzard o Riot entre otras, poniendose en la piel de personajes de Warcraft y de League of Legends! Desde aquí le agracedemos enormemente que se haya pasado pos nuestra casa a charlar un rato con nosotros! Y para acabar, comentamos el polémico artículo de Jason Kehe sobre Brandon Sanderson en la revista Wired. Brandon Sanderson, aclamado escritor creador del Cosmere y de sagas como Nacidos de la Bruma (Mistborn), el Archivo de las Tormentas, el Aliento de los Dioses o Elantris, ha sido atacado duramente por esta rata miserable que es Jason Kehe. Os comentamos lo que opinamos al respecto!", false);
			Episode episode3x17 = new Episode((byte) 3, (byte) 17, "El Reboot de Harry Potter, Outside de Brandon Sanderson, reseña: Dungeons & Dragons", "https://i.ytimg.com/vi/roAcPJZUjXc/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDyi01aGZ7-DRKJub47DFYjNQyrfQ", "https://www.youtube.com/watch?v=roAcPJZUjXc", "https://www.ivoox.com/3x17-cosas-como-reboot-harry-potter-outside-audios-mp3_rf_106430590_1.html", "2:00:38", "Canon", " Primero comentamos el reboot de Harry Potter, en formato de una nueva serie de HBO Max, adaptando los libros de J.K. Rowling. Después analizamos el articulo de Brandon Sanderson, autor del Cosmere, en el que se abre en canal a raíz del artículo publicado por Jason Kehe en la revista Wired. Para acabar, una divertida y nostálgica reseña de la película Dungeons & Dragons, la habéis visto?", false);
			Episode episode3x18 = new Episode((byte) 3, (byte) 18, "Fan cast español El Archivo de las Tormentas con IA, moda Superpop, saga Zelda", "https://i.ytimg.com/vi/Wjb-0BNIvxM/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCnaQNDWIsZDKXqpy7f46xERwg3Tg", "https://www.youtube.com/watch?v=Wjb-0BNIvxM", "https://www.ivoox.com/3x18-cosas-como-fancast-del-archivo-las-audios-mp3_rf_107625642_1.html", "2:36:29", "Canon", "En la primer a sección os traemos un contenido insuperable, el fan cast de El Archivo de las Tormentas del Cosmere de Brandon Sanderson, pero con imágenes de los actores caracterizados mediante una IA, ha sido un currazo así que os pedimos que le deis cariño!! Después, comentamos la revista Superpop, concretamente los consejos de moda que se daban en aquella época para la vuelta al cole. Antes muerta que sencilla, ya sabéis. Y para cerrar el programa, un repaso a todos los videojuegos de la saga Zelda, con nuestros comentarios e impresiones de los que más nos gustaron en su momento, pura nostalgia videojueguil.", false);
			Episode episode3x19 = new Episode((byte) 3, (byte) 19, "Fan cast El Archivo de las Tormentas con IA, Zelda TOTK, Eurovision 2023", "https://i.ytimg.com/vi/baCUb--9c4w/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAEkL5QTZbYJTO7Ddzc8c_i7XkY-Q", "https://www.youtube.com/watch?v=baCUb--9c4w", "https://www.ivoox.com/3x19-cosas-como-fancast-archivo-tormentas-audios-mp3_rf_108515626_1.html", "2:24:33", "Canon", "Esta semanita volvemos con la segunda parte del Fan Cast de El Archivo de las Tormentas, perteneciente al universo del Cosmere escrito por Brandon Sanderson, esta vez es el casting 'bien' con actores internacionales, además hemos creado imágenes originales mediante una IA para  ilustrarlo. En la segunda sección, analizamos las nuevas mecánicas jugables de The Legend of Zelda Tears of the Kingdom, las cuales han supuesto una revolución en los videojuegos de la mano de Nintendo. Vuelven Link y Zelda, esta vez a la Nintendo Switch. Para acabar, como ya es costumbre todos los años, comentamos la gala de Eurovisión 2023, cuaya ganadora fue Suecia con la interpretación de Loreen. Charlamos si nos ha parecido justo o no, y quién pensábamos que merecía ganar.", false);
			Episode episode3x20 = new Episode((byte) 3, (byte) 20, "Malaz: Memorias de Hielo, Moldeadores de Alma, nuevo libro de Patrick Rothfuss", "https://i.ytimg.com/vi/TWB--TY0x4Q/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBPeWvNLrYkcC4CZuox5JsHmjtHgA", "https://www.youtube.com/watch?v=TWB--TY0x4Q", "https://www.ivoox.com/3x20-cosas-como-malaz-memorias-hielo-moldeadores-audios-mp3_rf_108972596_1.html", "2:05:00", "Canon", "En el programa de hoy os traemos las primeras impresiones de Malaz 3 Memorias de Hielo de Steven Erikson, os contamos lo que nos está pareciendo este libro, después de los sentimientos encontrados que tuvimos en Malaz 1 y 2. Por otro lado os contamos todo sobre los moldeadores de alma, y las conexiones y teorías que puede haber detrás de estos extraños fabriales, lo habíais pensado alguna vez? Y para acabar, charlamos sobre el nuevo libro de Patrick Rothfuss que no es el que esperábamos, pero que puede ser un pasito más hacia la salida del último libro de las crónicas del Asesino de de Reyes y la historia de Kvothe.", false);
			Episode episode3x21 = new Episode((byte) 3, (byte) 21, "Diablo IV, Los Tonos de Roshar con @Pabloglezcas y test de ligue Superpop", "https://i.ytimg.com/vi/PBPS_wxWwEk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD2moLBl-idW2Ndd_6-eqb9Ra3o4Q", "https://www.youtube.com/watch?v=PBPS_wxWwEk", "https://www.ivoox.com/3x21-cosas-como-diablo-iv-tonos-puros-audios-mp3_rf_110048632_1.html", "2:31:59", "Canon", "Esta semana y aprovechando el reciente lanzamiento de Diablo IV, el último juego de Blizzard, charlamos sobre la franquicia y os contamos nuestras primeras impresiones de Diablo IV, aprovechamos además para hacer un repaso a la saga! En la segunda sección nos acompaña @Pabloglezcas  , creador de contenido de los videos los Tonos de Roshar, comentamos cómo hace los videos, hablamos del Cosmere de Brandon Sanderson y sobre la música en Roshar. Para cerrar, una divertidísima sección en el que hacemos un test de ligar de la revista Superpop, en serio no tiene desperdicio!", false);
			Episode episode3x22 = new Episode((byte) 3, (byte) 22, "Combates Imposibles, Starfield, libros de fantasía con Tamara de @Cosmere_es", "https://i.ytimg.com/vi/5uAmQrAUq_I/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDT6YXfXNkvNYYuL1JgER8UkkjJwg", "https://www.youtube.com/watch?v=5uAmQrAUq_I", "https://www.ivoox.com/3x22-cosas-como-combates-imposibles-starfield-literatura-audios-mp3_rf_110549060_1.html", "2:14:05", "Canon", "Para empezar la final de Combates Imposibles, cuyos finalistas son Tyrion Lannister de Juego de Tronos, Elon Musk propietario de Twitter o Tesla, Vlad Tepes propietario de un castillo con gente empalada, y Rafa Nadal propietario de un Kia. Después comentamos el reciente anuncio del último juego de Bethesda, Starfield, donde podrás explorar un inmenso universo espacial con tus propias naves personalizables. Starfield es la primera IP nueva de Bethesda en 25 años! Y para acabar, Tamara de @Cosmere_es nos cuenta cuáles son los libros de fantasía que más le han marcado a parte de la obra de Brandon Sanderson y el Cosmere, libros que son de obligada lectura para todo aquel o aquella amante de los libros de fantasía.", false);
			Episode episode3x23 = new Episode((byte) 3, (byte) 23, "Season Finale Temporada 3", "https://i.ytimg.com/vi/AXDchl0fRHk/maxresdefault.jpg", "https://www.youtube.com/watch?v=AXDchl0fRHk", "https://www.ivoox.com/3x23-cosas-como-season-finale-audios-mp3_rf_112042580_1.html", "2:27:27", "Canon", "Otro año más, y otra temporada más de nuestro podcast, y para finalizar os traemos un Season Finale de la tercera temporada! Comentamos el año, lo que más nos ha gustado, las expectativas que teníamos y si se han cumplido o no, además comentamos varias ideas y proyectos que tenemos para la temporada 4, porque esto no se acaba!!! Además una sección con los inicios de algunos de los miembros de Puente4Podcast, una mirada al pasado! Para acabar, sección de himnos de la comunidad, con regalitos sopresa y una sección propiamente dicha de saludos a la comunidad Patreon!", false);

			Episode episode4x01 = new Episode((byte) 4, (byte) 1, "Baldur's Gate 3 GOTY, One Piece Live Action (no spoilers), H.P. Lovecraft", "https://i.ytimg.com/vi/mcUi41gUfCo/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAwo5zuGihapur_EcwLtGzI-2ht-w", "https://www.youtube.com/watch?v=mcUi41gUfCo&t=6371s", "https://www.ivoox.com/4x01-cosas-como-baldur-s-gate-3-one-piece-audios-mp3_rf_116010809_1.html", "2:00:17", "Canon", "En primer lugar y como no podía ser de otra manera, hablamos del Baldur's Gate 3, el último juego de Larian Studios, que se postula como un firme candidato para los GOTY de este año, os contamos lo que nos ha parecido y si deberíais jugarlo! Welcome to Faerun! Después, comentamos las primeras impresiones del Live Action de One Piece creado por Netflix, con  muchísimas dudas iniciales y miedo, esta serie al final ha calado entre los seguidores, recordad que la comentaremos de manera completa y con spoilers en el siguiente Archivo! Y para cerrar, una guía introductoria para leer al creador del Cthulhu, H.P. Lovecraft, os contamos por donde empezar a leer su obra, y os guiamos para que contaros cómo se estructura para que empecéis por donde más os convenga!!", true);

			Archive archivex001 = new Archive((byte) 1, "El Archivo de las Tormentas: Reseña Brandon Sanderson", "https://i.ytimg.com/vi/qZwE2LDw42E/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLASV5xu-_TjTt0VYh0u-Ih0HI8K9A", "https://www.youtube.com/watch?v=qZwE2LDw42E", "https://www.ivoox.com/arch-1-brandon-sanderson-archivo-de-audios-mp3_rf_62210556_1.html", "2:09:39", "Archivo", "Estrenamos un nuevo formato! Los Archivos del Puente 4 serán programas especiales, de tipo monográfico que se irán publicando cada cierto tiempo de forma paralela a los programas normales. En este Archivo Primero, hablamos de Brandon Sanderson y su saga El Archivo de las Tormentas. Si como a nosotros os gusta la lectura y las buenas historias, en este programa desgranamos los tres primeros libros de esta decalogía.", true);
			Archive archivex002 = new Archive((byte) 2, "EL RITMO DE LA GUERRA: Reseña Brandon Sanderson", "https://i.ytimg.com/vi/0lJAb6Ygmw8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCUN67qgBuXpyqo_amx-zCFWKfxQg", "https://www.youtube.com/watch?v=0lJAb6Ygmw8", "https://www.ivoox.com/arch-2-brandon-sanderson-ritmo-de-audios-mp3_rf_64366321_1.html", "2:42:08", "Archivo", "Comentamos y analizamos en profundidad el 4º libro de la saga el Archivo de las Tormentas, el Ritmo de la Guerra. Diseccionamos personajes, trama, contexto y mucho más. Hacemos también un resumen de cuáles han sido nuestras partes favoritas, y qué partes nos han gustado menos Al final del programa, además, comentamos los nexos de esta saga con otros libros del Cosmere de Brandon Sanderon.", true);
			Archive archivex003 = new Archive((byte) 3, "Brandon Sanderson y el Imperio Final", "https://i.ytimg.com/vi/NWFJX0cVybk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAOt_YAu7QD5rLlzSOxvexvOZSe5w", "https://www.youtube.com/watch?v=NWFJX0cVybk&t=650s", "https://www.ivoox.com/arch-3-brandon-sanderson-imperio-final-audios-mp3_rf_66051152_1.html", "1:58:39", "Archivo", "Reseña de el Imperio Final de Brandon Sanderson, de su conocida saga Nacidos de la Bruma, o Mistborn en su versión inglesa. Hablamos sobre el argumento, personajes, sistema de magias, partes favoritas, críticas y mucho más! Escucha el podcast y descubre estos libros basados en el Cosmere, y escucha lo que opinamos del primer libro El Imperio Final, de la saga Nacidos de la Bruma, de Brandon Sanderson.", true);

			Comentary testCommentary1 = new Comentary("This is a test commentary, and is too short so i will put something more 1", LocalDate.now());
			Comentary testCommentary2 = new Comentary("This is a test commentary, and is too short so i will put something more 2", LocalDate.now());
			Comentary testCommentary3 = new Comentary("This is a test commentary, and is too short so i will put something more 3", LocalDate.now());
			Comentary testCommentary4 = new Comentary("This is a test commentary, and is too short so i will put something more 4", LocalDate.now());
			Comentary testCommentary5 = new Comentary("This is a test commentary, and is too short so i will put something more 5", LocalDate.now());

			Favorite testFavorite = new Favorite();

			List<Season> seasonList = Arrays.asList(season1, season2, season3, season4);
			List<Episode> episodeListS1 = Arrays.asList(episode1x01, episode1x02, episode1x03, episode1x04, episode1x05, episode1x06, episode1x07, episode1x08, episode1x09, episode1x10,
					episode1x11, episode1x12, episode1x13, episode1x14, episode1x15, episode1x16, episode1x17, episode1x18, episode1x19, episode1x20, episode1x21, episode1x22, episode1x23);
			List<Episode> episodeListS2 = Arrays.asList(episode2x01, episode2x02, episode2x03, episode2x04, episode2x05, episode2x06, episode2x07, episode2x08, episode2x09, episode2x10,
					episode2x11, episode2x12, episode2x13, episode2x14, episode2x15, episode2x16, episode2x17, episode2x18, episode2x19, episode2x20, episode2x21, episode2x22, episode2x23,
					episode2x24, episode2x25);
			List<Episode> episodeListS3 = Arrays.asList(episode3x01, episode3x02, episode3x03, episode3x04, episode3x05, episode3x06, episode3x07, episode3x08, episode3x09, episode3x10,
					episode3x11, episode3x12, episode3x13, episode3x14, episode3x15, episode3x16, episode3x17, episode3x18, episode3x19, episode3x20,episode3x21, episode3x22, episode3x23);
			List<Episode> episodeListS4 = Arrays.asList(episode4x01);


			puente4podcast.addPodcastUser(adminUser);
			puente4podcast.addPodcastUser(testUser);
			puente4podcast.addAllSeasons(seasonList);
			puente4podcast.addArchive(archivex001);
			puente4podcast.addArchive(archivex002);
			puente4podcast.addArchive(archivex003);
			season1.addAllEpisodes(episodeListS1);
			season2.addAllEpisodes(episodeListS2);
			season3.addAllEpisodes(episodeListS3);
			season4.addAllEpisodes(episodeListS4);
			episode1x01.addComentary(testCommentary1);
			episode1x01.addComentary(testCommentary2);
			episode1x01.addComentary(testCommentary3);
			episode1x01.addComentary(testCommentary4);
			episode1x01.addComentary(testCommentary5);
			episode1x01.addFavorite(testFavorite);
			testUser.addFavorite(testFavorite);
			testUser.addComentary(testCommentary1);
			testUser.addComentary(testCommentary2);
			testUser.addComentary(testCommentary3);
			testUser.addComentary(testCommentary4);
			testUser.addComentary(testCommentary5);

			podcastRepository.save(puente4podcast);
			podcastUserRepository.save(adminUser);
			podcastUserRepository.save(testUser);
			seasonRepository.saveAll(seasonList);
			archiveRepository.save(archivex001);
			archiveRepository.save(archivex002);
			archiveRepository.save(archivex003);
			episodeRepository.saveAll(episodeListS1);
			episodeRepository.saveAll(episodeListS2);
			episodeRepository.saveAll(episodeListS3);
			episodeRepository.saveAll(episodeListS4);
			favoriteRepository.save(testFavorite);
			comentaryRepository.save(testCommentary1);
			comentaryRepository.save(testCommentary2);
			comentaryRepository.save(testCommentary3);
			comentaryRepository.save(testCommentary4);
			comentaryRepository.save(testCommentary5);
		};
	}
}
